### ISSUE TITLE
Report folder naming

### ISSUE THREAD

**Issue by kolomenkin** [nvuillam/mega-linter#119]
Maybe it is a good idea to rename default dir for reports to from `report` to `.report`? So excluding it by default at any directory level will less likely affect any useful directory in linted project?

I can easily imaging to have folder `report` with some report generator code inside.

**Comment by nvuillam** [comment]
Super-Linter uses report, so I prefer to remain compliant , but it's possible to override the folder name using configuration variable OUTPUT_FOLDER :) 

https://nvuillam.github.io/mega-linter/configuration/#shared-variables
