### ISSUE TITLE
Docker image optimization proposal

### ISSUE THREAD

**Issue by kolomenkin** [nvuillam/mega-linter#122]
1. Maybe you would like to experiment with a command line setting `--cache-from` for `docker build`.
https://docs.semaphoreci.com/ci-cd-environment/docker-layer-caching/#about-cache-from

It allows CI to reuse image layers from previous builds even if local build agent image cache does not have them. I'm not sure. Maybe this is not a real issue due to good docker cache in GitHub actions. Or because all layers are updated and regenerated too frequently.

If we reuse layers more - it will take less time for end users to download them. And it will take less disk space.

Please note I did not use this command line option before. I'm just going to try it in CI on my current project.

2. I would also recommend to reorder blocks inside of `Dockerfile` so that dependencies which are changed more frequently and moved later.

**Comment by kolomenkin** [comment]
Googling shows first proposal is implemented in GitHub Actions:
https://github.com/marketplace/actions/build-docker-images-using-cache#how-it-works

**Comment by nvuillam** [comment]
Good proposition !
Can you see how it works on your project and try to apply it here ? Probably in the default `mega-linter.yml` we propose ?

I see 2 axes : 
- Using --cache for docker build in job deploy-DEV.yml : you're totally right that we should not have to wait for 30 mn to validate a typo fix in python !
- Do not use --cache for docker build in deploy-PROD and deploy-RELEASE: as linters are usually not specified with a version, we must install their latest version everytime we generate a new "official" docker image

**Comment by nvuillam** [comment]
Another thing we could do in deploy-DEV is to leverage more capabilities of skip-duplicate-jobs GH Action: https://github.com/fkirc/skip-duplicate-actions#option-2-skip-individual-steps

We could for example always use docker build cache when Dockerfile has not been updated

**Comment by kolomenkin** [comment]
Yesterday I tried `--cache-from`
There are some complicated requirements like we need to add env variable for docker tool during building the image we want to use for cache later.

I need to experiment more.
So this proposal is not ready right now.

> Do not use --cache for docker build in deploy-PROD and deploy-RELEASE: as linters are usually not specified with a version, we must install their latest version everytime we generate a new "official" docker image

Using the layer cache should not prevent you from using fresh linters once you use `--pull` during docker build. And your production should always use `--pull`.

**Comment by kolomenkin** [comment]
I just realized Dockerfile is started with a pack of `FROM xxxx` lines. I.e. changing of any linter images should lead to full image rebuild.

And layer cache will not help. Reordering blocks will not help.

**Comment by nvuillam** [comment]
If the FROM are put later in the dockerfile, would it be better ?

**Comment by kolomenkin** [comment]
I'm not sure. I do not have enough experience with multistage.
It may happen early stages to not make problem for independent layers of next stages.
I need to check.

**Comment by kolomenkin** [comment]
Ok. I made some experiments.

Having lots for `FROM` in the beginning of Docker file does not affect following layers until they copy some files frome those images.

I.e. their order does not matter. Adding some unused `FROM` does not affect anything except it will force pull those image during the build first time.

So this is still a good idea to sort blocks which initialize different linters in the order of their update frequency.

**Comment by nvuillam** [comment]
> So this is still a good idea to sort blocks which initialize different linters in the order of their update frequency.

The problem is that any linter can release a new version anytime, there is no calendar ,so I don't have a clue about what could be this order :/

**Comment by kolomenkin** [comment]
In this case do not mind.

Maybe after some time you will gather statistics like some linters are updated twice a year and others 50 times a year.

**Comment by kolomenkin** [comment]
By the way.

`--cache-from` does not work if image was not built with `--build-arg BUILDKIT_INLINE_CACHE=1`

`--build-arg BUILDKIT_INLINE_CACHE=1` does not affect anything until BuildKit (experimental image builder) is activated.

To activate BuildKit you need to do one of the following:
1) set environment outside of docker `DOCKER_BUILDKIT=1` with `docker build`
2) use command `docker buildx` which needs additional manual activation in `config.json` or in Docker Desktop settings

So I would say this feature needs too much changes. And it is too experimental. And I do not expect breakthrough advantages from using it.

**Comment by nvuillam** [comment]
Agreed 
Let's think of other improvements :)
