### ISSUE TITLE
linter `file_names` customization

### ISSUE THREAD

**Issue by kolomenkin** [nvuillam/mega-linter#138]
## Problem

I have the following problem. My project contains a number of Docker files with names like `Dockerfile-*`.
I want to lint them. But Dockerfile liters do not find them.

## Proposal

1. Add possibility to customize `file_names` for particular linter and/or globally

2. Optional: Add possibility to customize `file_extensions` for particular linter and/or globally

3. Add support for regular expressions of simple file masks inside of `file_names`.

4. Optional: Compile regular expressions used many times: `filter_regex_include`, `filter_regex_exclude`, `file_names`
https://docs.python.org/3/library/re.html#re.compile

5. Optional: Join multiple regular expressions to match faster (when we need to match an array of regular expressions to an array of files):
https://stackoverflow.com/a/3040797/739731

6. (Not related): Some documentation is missing for config options. For example `REPORT_OUTPUT_FOLDER`, `GITHUB_WORKSPACE` and others

What do you think about these proposals?
What is a good idea to implement and what is not?

P.S. I'm ready to implement these features. I just want to know they will not break something I do not know. Or maybe you have better ideas how to improve the code or solve my problem.

**Comment by kolomenkin** [comment]
Related PR:
https://github.com/nvuillam/mega-linter/pull/139

**Comment by nvuillam** [comment]
I agree with all your propositions :)

But about dockerfile, I think we should directly update the hardcoded descriptor (with regex) because anything containing "Dockerfile" and with no extension should be linted (same for Jenkinsfile probably)

Reviewing your nice PR

**Comment by nvuillam** [comment]
Closed by #139
