### ISSUE TITLE
Can't reach via twitter

### ISSUE THREAD

**Issue by jlongman** [nvuillam/mega-linter#208]
First, tried to say hi via the blue bird but the "This account doesn't exist". It's linked in the footer of your doc home page:
- https://nvuillam.github.io/mega-linter/ footer links to 
- https://twitter.com/nvuillam
which gives the missing account error.  

Expectation: Either a valid twitter account should be linked or the link should be removed.  Is there a valid twitter account?

What I was trying to say was: Super happy to find this project as I've run up against the limitations of the bash version when adapting it for bitbucket, and to a lesser degree codebuild.  Additionally in my port of the super-linter I parse the linter annotations and make line-by-line annotations against the bitbucekt PR api  (for example) as well as adding xunit output.

Also thrilled to see flavors and am curious about docker-in-docker as a solution for certain environments.  I've still not scanned the docs but I'm hoping the flavors still detect all formats and warn or fail if the flavor is incomplete and/or a separate lightweight image can do that.

Great stuff, hoping to throw up a PR soon (but I must admit this is a bit shaving the yak for me).

**Comment by nvuillam** [comment]
Hi, thanks a lot for the feedback, I just corrected my twitter link, which is https://twitter.com/NicolasVuillamy :) 

I see you played with BitBucket... would you make a tiny PR in the README so I can add it in the list of installation CI systems ? ( then later in the config generator). Or just paste here your bitbucket workflow configuration and I'll do the rest :)

I don't get exactly what you do with super-linter logs, but it seems about detailed repoters, so I'm sure that we can do more with Mega-Linter reporters:
- maybe a new BitBucketCommentReporter ? or something more ? Reporters architecture allow to have as many as we want, so your PR would be very welcome :)
- [building a reviewDog reporter](https://github.com/reviewdog/reviewdog/issues/841) ... maybe it would help with your requirement ? ( I see they have a [BitBucket reporter](https://github.com/reviewdog/reviewdog#reporter-bitbucket-code-insights-reports--reporterbitbucket-code-report) )

Please let me know your thoughts, and thanks again for your interest 🚀
