### ISSUE TITLE
Optimization python libs layer?

### ISSUE THREAD

**Issue by jlongman** [nvuillam/mega-linter#217]
Hey, so I've been poking around.  

In the short term I'm hacking some things in in a very ugly way.  I'll admit that my experience is patchy/incomplete with docker and coding in python and I'm working mostly on my laptop rather than using github automations, for example.  Oh and patchy with github actions too.

One of the things I noticed testing with bitbucket is the image build time is long because of the `setup.py` refetching everything when I need to change a single python file.  

Does adding a python lib layer make sense as a PR?

I quickly hacked something like:
```
##################
# Get base image #
##################
FROM python:3.8-alpine

ARG GITHUB_VERSION=4.20.0
LABEL GITHUB_VERSION=v$GITHUB_VERSION

# APK Packages used by mega-linter pylib
# this must be a subset of main libraries 
# this selection is a little shotgun, it appears to work though
# what happens if they don't match?
RUN apk add --update --no-cache \
    coreutils \
    curl \
    file \
    gcc \
    gnupg \
    icu-libs \
    jq \
    krb5-libs \
    libcurl libintl libssl1.1 libstdc++ \
    libffi-dev \
    linux-headers \
    make \
    musl-dev \
    py3-setuptools \
    readline-dev

################################
# Installs python dependencies #
################################
COPY megalinter /megalinter
RUN python /megalinter/setup.py install --user

###########################
# Get the build arguments #
###########################
ARG BUILD_DATE
ARG BUILD_REVISION
ARG BUILD_VERSION

#################################################
# Set ENV values used for debugging the version #
#################################################
ENV BUILD_DATE=$BUILD_DATE
ENV BUILD_REVISION=$BUILD_REVISION
ENV BUILD_VERSION=$BUILD_VERSION


#########################################
# Label the instance and set maintainer #
#########################################
LABEL com.github.actions.name="Mega-Linter Python Requirements" \
      com.github.actions.description="Python libs for the ultimate linters aggregator to make sure your projects are clean" \
      maintainer="Nicolas Vuillamy <nicolas.vuillamy@gmail.com>" \
      org.opencontainers.image.created=$BUILD_DATE \
      org.opencontainers.image.revision=$BUILD_REVISION \
      org.opencontainers.image.version=$BUILD_VERSION \
      org.opencontainers.image.authors="Nicolas Vuillamy <nicolas.vuillamy@gmail.com>" \
      org.opencontainers.image.url="https://nvuillam.github.io/mega-linter" \
      org.opencontainers.image.source="https://github.com/nvuillam/mega-linter" \
      org.opencontainers.image.documentation="https://nvuillam.github.io/mega-linter" \
      org.opencontainers.image.vendor="Nicolas Vuillamy" \
      org.opencontainers.image.description="Lint your code base with GitHub Actions - Python libs"
```

which is pushed as `jlongman/mega-linter-pylib:v$GITHUB_VERSION` (well `jlongman/mega-linter-pylib:test` for now).

then into the main Dockerfile and the flavor I was targeting as a smaller test flavor:

```
# FROM jlongman/mega-linter-pylib:v$GITHUB_VERSION as mega-linter-pylib
FROM jlongman/mega-linter-pylib:test as mega-linter-pylib
# etc
COPY --from=mega-linter-pylib /root/.local /root/.local
COPY megalinter /megalinter
```

Note, reviewing this I can't find where I took `GITHUB_VERSION` from.  The intention is to strongly link the pylib image with any of the users images contexts.

I might look at pushing the hacky version for review, in case it helps comprehension.  Looking at it the way the autogenerated Dockerfiles are done is not included in what I've done, but I'm not sure if this is worth the effort without an intention to merge.  

As I said, it allowed me to iterate faster, in this particular case I was trying to set up the git proxy so that bitbucket's git would automatically authenticate with the pipeline's ownership context, as well as solve a misunderstanding of how GitPython was working locally.

**Comment by jlongman** [comment]
Illustrated here - hftegps://github.com/jlongman/mega-linter/pull/1

Very hacky, but I'm not going to polish it unless it's interesting. I could maintain it as a branch I merge in for specific dev phases (and then remove) if it ends up being uninteresting for any number of good reasons, I'm sure.

**Comment by nvuillam** [comment]
I love the idea, it's kind of boring to re-run the full build just because you changed a single line in mega-linter python core !

This would dramatically improve contributor experience :)

I'll think of a way to make it less "hacky" , probably something like using conditions in github action workflow to select it has to be run with image full build or light build

**Comment by nvuillam** [comment]
I implemented "quick build" mode for contributors :)

I've not understood completely the python-lib stuff, so i've not used it,  but does it work for your requirement ?
If you think python-lib stuff can again improve perfs, please tell :)

 - When a branch is created and code is pushed, a **GitHub** Action is triggered for building the new **Docker** container with the new codebase
  - During development, if all you updated is python code, you can write `quick build` in the commit message body to benefit from a quicker build (about 15 minutes): only python files are copied over nvuillam/mega-linter:test-YOURUSERNAME-YOURBRANCH or nvuillam/mega-linter:latest if a previous full run has not been performed yet
  - You can [filter the performed tests](https://docs.pytest.org/en/stable/usage.html#specifying-tests-selecting-tests) by writing `TEST_KEYWORDS=my keywords` in the commit message body. Example: `TEST_KEYWORDS=kubernetes_kubeval_test`
  - The last commit before the validation of a Pull Request must be a full build with all tests (about 45 minutes)

Not sure the TEST_KEYWORDS is orking perfectly , i struggled with bash :/
