### ISSUE TITLE
Missing properties in JSON Schema

### ISSUE THREAD

**Issue by JimmyTournemaine** [nvuillam/mega-linter#321]
**Describe the bug**

`.mega-linter.yml` is not validated because of missing *jsonschema* properties.
If found that `UPDATED_SOURCES_*` are missing but maybe some others should be missing too.

```plain
❌ [ERROR] .mega-linter.yml
    Validating .mega-linter.yml against schema from https://raw.githubusercontent.com/nvuillam/mega-linter/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json ...
    
    Errors:
    [
      {
        keyword: 'additionalProperties',
        dataPath: '',
        schemaPath: '#/additionalProperties',
        params: { additionalProperty: 'UPDATED_SOURCES_REPORTER' },
        message: 'should NOT have additional properties'
      }
    ]
    
    ❌ .mega-linter.yml is invalid
```

**To Reproduce**

1. Go to your project working directory
2. Declare `UPDATED_SOURCES_REPORTER: false` in `.mega-linter.yml`
3. Run Mega-Linter (with the YAML V8R)
4. See error in V8R report

**Expected behavior**
`UPDATED_SOURCES_REPORTER` should be accepted as described in the [documentation](https://nvuillam.github.io/mega-linter/reporters/UpdatedSourcesReporter/#configuration)

**Additional context**

Run in a local docker container using:
```bash
docker run  -v $(pwd):/tmp/lint nvuillam/mega-linter:v4
```

**Workaround**

Excludes `.megalinter.yml` from V8R Linter using `YAML_V8R_FILTER_REGEX_EXCLUDE: '.mega-linter.yml'`

**Comment by nvuillam** [comment]
Good catch :)
Fo you feel confident making a PR or shall I do it ? :)

**Comment by JimmyTournemaine** [comment]
I will for seeing how to contribute because I've to make another pull request to propose an enhancement about eslint ;)
