### ISSUE TITLE
Respect .gitignore in mega-linter-runner

### ISSUE THREAD

**Issue by underyx** [nvuillam/mega-linter#348]
**Is your feature request related to a problem? Please describe.**

I ran `mega-linter-runner` on a local repository, which uses Terraform. Terraform clones dependencies into a `.terraform/` directory (just like `node_modules/` for `npm`). Our `.gitignore` ignores this with `**/.terraform/`, so I expected mega-linter-runner will understand that I don't want to lint this directory. However, I am getting results for various files within, such as

```
In /tmp/lint/deploy/terraform/dev/.terraform/modules/deployment.eks/examples/launch_templates/pre_userdata.sh line 1:
```

**Describe the solution you'd like**

Read exclude patterns from `.gitignore` and append them to all the other user-defined excludes.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by nvuillam** [comment]
That's indeed an interesting evolution :)

Meanwhile, you can use FILTER_REGEX_EXCLUDE= "(\.terraform/)" :)

**Comment by nvuillam** [comment]
In progress :)
