### ISSUE TITLE
editorconfig-checker bug causing issues in mega-linter

### ISSUE THREAD

**Issue by omusavi** [nvuillam/mega-linter#367]
**Describe the bug**
I opened an issue for [editorconfig-checker](https://github.com/editorconfig-checker/editorconfig-checker/issues/156), but this will likely affect mega-linter users so also posting here as an FYI. Also there are some potential mega-linter fixes here.

**To Reproduce**

1. Run mega-linter with editorconfig-checker with lots of files
2. Run multiple times  (depending on number of files linted)

**Expected behavior**
No issues

**Actual behavior**
At some point, we get rate limited and builds will fail with the following error:
```
ERROR: TypeError: json.map is not a function
    at /node_modules/editorconfig-checker/dist/lib.js:160:22
    at step (/node_modules/editorconfig-checker/dist/lib.js:52:23)
    at Object.next (/node_modules/editorconfig-checker/dist/lib.js:33:53)
    at fulfilled (/node_modules/editorconfig-checker/dist/lib.js:24:58)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

**Screenshots**

**Additional context**
If it is not set, `--skip-update-check` should be set in the editorconfig-checker command line for mega-linter. That won't fix the issue now because of the bug, but in the future that will likely need to be set or rate limiting will still occur.

**Comment by nvuillam** [comment]
To be honest, I always disable .editorconfig checks... :)
Please can you notify me to add `--skip-update-check` by default in the list of arguments ?

**Comment by omusavi** [comment]
Looks like the change was reverted and the `--skip-update-check` field is no longer in the runner. I think the only necessary fix now is to make sure the version of editorconfig-checker javascript package included in mega-linter is at least 4.0.1?

**Comment by nvuillam** [comment]
When i integrated editorconfig-checker, theire `-version` argument provoked a crash , so i have 0.0.0 displayed by default in Mega-Linter :/

I'll check if they fixed the bug so we can know which version is used :)

meanwhile, Mega-Linter auto-updates itself with latest versions of linters every night, and it's included in **insiders** / ** latest** version (not V4), so if you use insiders version you should have the latest editorconfig-checker one :)

**Comment by omusavi** [comment]
This is fixed in editorconfig-checker and I also confirmed the version in mega-linter is now correct!
