### ISSUE TITLE
Missing ERROR_ON_MISSING_EXEC_BIT property in configuration schema

### ISSUE THREAD

**Issue by vsimon** [nvuillam/mega-linter#369]
**Describe the bug**

Minor issue:

The ERROR_ON_MISSING_EXEC_BIT variable mentioned in https://nvuillam.github.io/mega-linter/descriptors/bash_bash_exec/ seems to be missing in https://raw.githubusercontent.com/nvuillam/mega-linter/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json

**Comment by nvuillam** [comment]
Solved :)
Thanks for reporting :)

**Comment by vsimon** [comment]
Thanks for solving it super fast! 🙏 

---

Another minor question I had about this particular variable, this repo is very well documented and uses conventions very well, was there a particular reason this wasn't named `BASH_EXEC_ERROR_ON_MISSING_EXEC_BIT`? 

ERROR_ON_MISSING_EXEC_BIT feels a bit like a top level config variable.

(In case changing it introduces backwards compatibility problems, both could be supported internally but the new one mentioned in the docs going forward)
