### ISSUE TITLE
ERROR_ON_MISSING_EXEC_BIT missing prefix BASH_EXEC_?

### ISSUE THREAD

**Issue by vsimon** [nvuillam/mega-linter#370]
This repo is very well documented and follows it's conventions very well! Noticed that one of the variables in https://nvuillam.github.io/mega-linter/descriptors/bash_bash_exec/ was named ERROR_ON_MISSING_EXEC_BIT (without a prefix name related to the linter) i.e. `BASH_EXEC_ERROR_ON_MISSING_EXEC_BIT`

`ERROR_ON_MISSING_EXEC_BIT` feels a bit like a top level config variable.

(In case changing it introduces backwards compatibility problems, both could be supported internally but the new one mentioned in the docs going forward)

**Comment by nvuillam** [comment]
ERROR_ON_MISSING_EXEC_BIT is a legacy variable of super-linter, here just for to keep compatibility for former Super-Linter users migrating to Mega-Linter , so I prefer to not display it at the top level, as it is a variable only used by a single linter

The variable to use to disable errors for bash-exec is `BASH_EXEC_DISABLE_ERRORS` ^^

https://nvuillam.github.io/mega-linter/descriptors/bash_bash_exec/

**Comment by vsimon** [comment]
@nvuillam Thanks I suspected that might be a compatibility reason...

**Comment by nvuillam** [comment]
You're welcome :)
