### ISSUE TITLE
Difficulty using linters that define 'active_only_if_file_found' inside a monorepo

### ISSUE THREAD

**Issue by vsimon** [nvuillam/mega-linter#374]
I am seeing an issue in the case of JSX in a monorepo but maybe there's an obvious solution. The structure is `.mega-linter.yml` at the root level with multiple subdirectories inside. The ` .eslintrc.json` is defined inside one of the subdirectories.

```
.
├── .mega-linter.yml
└── backend
└── webapp
    └── .eslintrc.json
```

This is the command I was attempting:
```
	docker run -t \
		-v ${PWD}:/tmp/lint \
		-e ENABLE_LINTERS=JSX_ESLINT \
		-e FILTER_REGEX_INCLUDE=webapp \
		nvuillam/mega-linter-javascript:v4
```
(using FILTER_REGEX_INCLUDE seems to work fine with the backend cases)

The issue I am seeing is that some linters, like the JSX one, specify [active_only_if_file_found](https://github.com/nvuillam/mega-linter/blob/master/megalinter/descriptors/jsx.megalinter-descriptor.yml#L18) and the [file check](https://github.com/nvuillam/mega-linter/blob/c3312dc35e70c565650475476a6fe0fe5c8a01f8/megalinter/Linter.py#L238) does not take into account other hints that could point to this file i.e. `JSX_ESLINT_CONFIG_FILE` or a `LINTER_RULES_PATH` containing a `.eslintrc.json` file. We could move `.eslintrc.json` to the root but that would take that file out of the project folder that contains `package.json`. We could mount the `webapp` subdirectory as the root workspace but this would omit the top-level `.mega-linter.yml` file from being utilized.

So what is left is manipulating the view of the directory structure through something like this:

```
	docker run -t \
		-v ${PWD}/webapp:/tmp/lint \
		-e ENABLE_LINTERS=JSX_ESLINT \
		-v ${PWD}/.mega-linter.yml:/tmp/.mega-linter.yml \
		-e MEGALINTER_CONFIG=../.mega-linter.yml \
		nvuillam/mega-linter-javascript:v4
```
What we are doing:
- we mount the "webapp" folder into the default workspace /tmp/lint. This finds the `.eslintrc.json` file but we no longer have the top-level .mega-linter.yml file.
- we mount `.mega-linter.yml` file into the /tmp directory (one level above the workspace).
- we set MEGALINTER_CONFIG to look one-level above from the workspace to find it.

This works but feels hacky. As far as I can tell, this only affects linters that have `active_only_if_file_found` defined.

Or maybe there is something I'm missing?

**Comment by nvuillam** [comment]
Sorry for the dekay, i'll have alook asap :)
