### ISSUE TITLE
Option to treat `Mega-Linter flavor [<flavor>] does not contain linters...` as an error

### ISSUE THREAD

**Issue by ottumm** [nvuillam/mega-linter#379]
The `FLAVOR_SUGGESTIONS` warning regarding using a flavor of Mega-Linter that doesn't include linters needed by some files found in a repo is very helpful, but it's also easy to miss in the output. I'd love an option to fail the run if the current flavor doesn't include all required linters. That way, I won't worry that I'm silently missing linter errors because I chose the wrong flavor (or a new type of file was added to the repo).

The current output is:
```shell
Mega-Linter flavor [python] does not contain linters RUBY_RUBOCOP.
As they are not available in this docker image, they will not be processed
To solve this problem, please either: 
- use default flavor nvuillam/mega-linter
- add ignored linters in DISABLE or DISABLE_LINTERS variables in your .mega-linter.yml config file located in your root directory
- ignore this message by setting config variable FLAVOR_SUGGESTIONS to false
```

**Comment by ottumm** [comment]
> Be careful, if you use such option and that someone adds a new linter that would catch a file type in your repo (that was not linted before), it would break ascending compatibility ^^

That's a good point, thanks for the warning!

> But it's harmless and easy to do, so PR is on its way

👏 👏 👏 thank you!

**Comment by nvuillam** [comment]
@ottumm nothing is free in this cruel world... that will cost you a star on a the repo :p ( and a tweet with #MegaLinter if you're in a good mood :p )
