### ISSUE TITLE
Use `.shellcheckrc` (if present) for shellcheck configuration

### ISSUE THREAD

**Issue by ottumm** [nvuillam/mega-linter#380]
Mega-Linter doesn't appear to respect the settings in the `.shellcheckrc` file (unless there's a setting I missed).

https://github.com/koalaman/shellcheck/wiki/Ignore#ignoring-one-or-more-type-of-error-forever

> As of v0.7.0 you can create a file .shellcheckrc in your home directory (or your project's base directory), and add disable directives to it

**Comment by nvuillam** [comment]
Please could you run your action with LOG_LEVEL=DEBUG and post the log here ?

It's strange, if 0.7.1 is present, shellcheck should find it

**Comment by ottumm** [comment]
Ugh, I created a test repo to get a minimal reproduction for this (https://github.com/ottumm/mega-linter-test/pull/1) and it appears that shellcheck is picking up the `.shellcheckrc` file correctly.

I'll keep investigating back in my actual repo, but I think I probably did something wrong over there, so this is not a bug. Sorry for the false alarm.
