### ISSUE TITLE
local custom lint rules for markdownlint are not found

### ISSUE THREAD

**Issue by ayyjohn** [nvuillam/mega-linter#396]
in the main directory of my project I created a test file `test_rule.js` that just throws a lint error on the first line of every linted file

```javascript
const { forEachLine, getLineMetadata } = require('markdownlint-rule-helpers');

module.exports = {
  "names": [ "first-line" ],
  "description": "Rule that reports an error for the first line",
  "tags": [ "test" ],
  "function": function rule(params, onError) {
    // Unconditionally report an error for line 1
    onError({
      "lineNumber": 1
    });
  }
};
```

for the purpose of getting custom rules set up and verifying they're working. 

After adding

```markdown
MARKDOWN_MARKDOWNLINT_ARGUMENTS: -r "./test_rule.js"
```
to my `.mega-linter.yml` the following error is produced 

```
--Error detail:
Cannot load custom rule ./test_rule.js: No such rule
```
which comes from [here](https://github.com/igorshubovych/markdownlint-cli/blob/master/markdownlint.js#L224) in markdownlint-cli

I tried a bunch of different versions, adding/dropping quotes, changing relativity, and messing with formatting to make sure I wasn't specifying the path wrong or something.

I installed markdownlint-cli via brew and was able to successfully see the custom rule executed by

markdownlint -r "test_rule.js" .

Does this have to do with the dockerization of `markdownlint`, and is there an option for me to push custom rules into the container so that they can be found?

**Comment by tpansino** [comment]
> Does this have to do with the dockerization of markdownlint

I think yes @ayyjohn. I've played around with the Docker images directly and the source code to be linted gets mounted under `/tmp/lint`. I'll bet your `./test_rule.js` isn't found because the linter is running in a different dir.

Try setting:

```yaml
MARKDOWN_MARKDOWNLINT_ARGUMENTS: "-r /tmp/lint/test_rule.js"
```

FWIW you can also customize where the source code gets mounted by changing `DEFAULT_WORKSPACE` in your `.mega-linter.yml`. Might have to play around with that if you want to use a relative path, otherwise a full path either to the rule or its parent dir should work.

**Comment by nvuillam** [comment]
Not tested yet... but did you try "-r ${WORKSPACE}/test_rule.js" ? :)

**Comment by ayyjohn** [comment]
Tom's version did work! 

I tried `MARKDOWN_MARKDOWNLINT_ARGUMENTS: -r "${DEFAULT_WORKSPACE}/custom_lint_rules"` and it tried to interpret it literally `Cannot load custom rule ${DEFAULT_WORKSPACE}/custom_lint_rules: No such rule`

I think I'm okay with this as is though, now that I know everything goes through `tmp/lint` 
thanks both!!
