### ISSUE TITLE
Reporting TAP files does not contain error messages

### ISSUE THREAD

**Issue by cezarfw** [nvuillam/mega-linter#413]
Hi,

I am finding it difficult to generate the TAP files.
I load the variables OUTPUT_FORMAT = "tap" -e OUTPUT DETAILS = "detail"
and the generated files present only the indexes, file names and "ok" | "not ok".

I've tried in several ways, including using the variable TAP_REPORTER but the result is always the same.

Has anyone been through this or can you help me ?? Please!!

![Captura de tela de 2021-04-12 12-19-43](https://user-images.githubusercontent.com/25337162/114419124-8b9bcb00-9b89-11eb-9b1f-ea8cba050757.png)
![Captura de tela de 2021-04-12 12-17-56](https://user-images.githubusercontent.com/25337162/114419131-8cccf800-9b89-11eb-8e08-9518a244226f.png)

cat report/tap/mega-linter-POWERSHELL_POWERSHELL.tap

**Comment by nvuillam** [comment]
I'll be completely honest... I've not given a big attention to TAP output... but it should work :)

Please can you try with `OUTPUT_DETAIL: detailed` ?

Maybe you could share your whole config file ?

**Comment by cezarfw** [comment]
Thanks for the return !!

It ends up being important TAP to generate report, in my case in Azure DevOps.

But rest assured, if I can help it will be a pleasure!

I tried in several ways, I will share the conf.

`APPLY_FIXES: all
ENABLE_LINTERS:
  - ANSIBLE_ANSIBLE_LINT
  - BASH_SHFMT
  - BASH_SHELLCHECK
  - DOCKERFILE_DOCKERFILELINT
  - YAML_YAMLLINT
  - YAML_PRETTIER
  - JSON_JSONLINT
  - KUBERNETES_KUBEVAL
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SQL_SQL_LINT
  - SPELL_MISSPELL
  - POWERSHELL_POWERSHELL
  - JAVASCRIPT_STANDARD
  - JAVASCRIPT_ES
FILTER_REGEX_EXCLUDE: '(\.cache|collections/ansible_collections/azure/azcollection|\.linters)'
YAML_YAMLLINT_FILTER_REGEX_EXCLUDE: '(\.mega-linter\.yml|roles|playbooks)'
YAML_PRETTIER_FILTER_REGEX_EXCLUDE: '(\.mega-linter\.yaml|mkdocs\.yml)'
YAML_V8R_FILTER_REGEX_EXCLUDE: '(\.mega-linter\.yml)'
YAML_YAMLLINT_ARGUMENTS: "--no-warnings"
BASH_FILTER_REGEX_EXCLUDE: "(lib)"
ANSIBLE_DIRECTORY: "."
MARKDOWN_FILTER_REGEX_EXCLUDE: '(license\.md|collections\/ansible_collections\/azure\/azcollection)'
MARKDOWN_DEFAULT_STYLE: "markdownlint"
PLUGINS:
  - https://raw.githubusercontent.com/nvuillam/mega-linter/master/.automation/test/mega-linter-plugin-test/test.megalinter-descriptor.yml
SPELL_MISSPELL_FILTER_REGEX_EXCLUDE: '(\.build/\*|\.git/\*|report/\*|docs/\*)'
DOCKERFILE_HADOLINT_ARGUMENTS: "--ignore DL3003 --ignore DL3007 --ignore DL3013 --ignore DL3016 --ignore DL3018 --ignore DL3028 --ignore DL4001 --ignore DL4006 --ignore SC2015 --ignore SC2016 --ignore SC2039 --ignore SC2086 --ignore SC1091"
SHOW_ELAPSED_TIME: true
VALIDATE_ALL_CODEBASE: true
FLAVOR_SUGGESTIONS: false
LINTER_RULES_PATH: .linters/config
TAP_REPORTER: true
TAP_REPORTER_SUB_FOLDER: tap
PRE_COMMANDS:
  - command: echo "This is Mega-Linter PRE_COMMAND on own Mega-Linter ! :)"
    cwd: "root"
POST_COMMANDS:
  - command: echo "This is Mega-Linter POST_COMMAND on own Mega-Linter ! :)"
    cwd: "workspace"
`

**Comment by cezarfw** [comment]
Ahh, I already made the change you commented but it didn't work.

If you have any ideas to help me, you are very welcome. In the meantime I am changing the code but I am not a python expert :(

**Comment by nvuillam** [comment]
Please could you run again with additional vvariables

```yaml 
OUTPUT_DETAIL: detailed
LOG_LEVEL: DEBUG
```

and attach the full log here ? (should be a big text ^^ )

**Comment by cezarfw** [comment]
I forgot to warn you in the last comment but I'm passing some variables through the docker run

'docker run --rm -e RUN_LOCAL=true -e OUTPUT_DETAILS=detailed -e OUTPUT_FORMAT=tap --name mega-linter -v $PWD:/tmp/lint nvuillam/mega-linter:v4'

I will add the variables and send them as soon as the execution is finished

**Comment by cezarfw** [comment]
Property OUTPUT_DETAIL is not allowed.yaml-schema: https://raw.githubusercontent.com/nvuillam/mega-linter/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json

Variable add to file .mega-linter.yml

**Comment by cezarfw** [comment]
[mega-linter.tar.gz](https://github.com/nvuillam/mega-linter/files/6300044/mega-linter.tar.gz)

**Comment by nvuillam** [comment]
OUTPUT_DETAILS, with a S please :)

**Comment by cezarfw** [comment]
Are you sure this variable rolls?

Property OUTPUT_DETAILS is not allowed.yaml-schema: https://raw.githubusercontent.com/nvuillam/mega-linter/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json

json schema does not exist, I'm passing via docker run as I mentioned earlier.

**Comment by cezarfw** [comment]
The code below is managing to generate the TAP, it still needs to be adjusted (I'm here hitting my head a little), if you can enjoy it, feel free.

`#!/usr/bin/env python3
"""
TAP reporter
https://testanything.org/
"""
import logging
import os

from megalinter import Reporter, config, utils


class TapReporter(Reporter):
    name = "TAP"
    scope = "linter"

    def __init__(self, params=None):
        # report_type is tap by default
        self.report_type = "tap"
        super().__init__(params)

    def manage_activation(self):
        # Super-Linter legacy variables
        output_format = config.get("OUTPUT_FORMAT", "")
        if output_format.startswith("tap"):
            self.is_active = True
            if config.get("OUTPUT_DETAIL", "") == "detailed":
                self.report_type = "detailed"
        # Mega-Linter vars (false by default)
        elif config.get("TEXT_REPORTER", "false") == "true":
            self.is_active = True
        else:
            self.is_active = False
        if self.is_active is True:
            # If TAP is active, we must lint file by file to have result file by file in TAP
            if self.master.cli_lint_mode == "list_of_files":
                self.master.cli_lint_mode = "file"
            elif self.master.cli_lint_mode == "project":
                self.is_active = False
                logging.warning(
                    f"Tap output is not available for {self.master.linter_name}"
                )

    def produce_report(self):
        self.master.cli_lint_mode == "list_of_files"
        tap_report_lines = ["TAP version 13",
                            f"1..{str(len(self.master.files))}"]
        # Convert file results in TAP
        for index, file_result in enumerate(self.master.files_lint_results):
            file_nm = utils.normalize_log_string(file_result["file"])
            tap_status = "ok" if file_result["status_code"] == 0 else "not ok"
            file_tap_lines = [f"{tap_status} {str(index + 1)} - {file_nm}"]
            if (
                self.report_type == "detailed"
                or file_result["stdout"] != ""
                and file_result["status_code"] != 0
            ):
                std_out_tap = (
                    file_result["stdout"].rstrip(
                        f" {os.linesep}") + os.linesep
                )
                std_out_tap = "\\n".join(std_out_tap.splitlines())
                std_out_tap = std_out_tap.replace(":", " ")
                detailed_lines = [
                    "  ---", f"  message: {std_out_tap}", "  ..."]
                file_tap_lines += detailed_lines
                tap_report_lines += file_tap_lines
        # Write TAP file
        tap_report_sub_folder = config.get("TAP_REPORTER_SUB_FOLDER", "tap")
        tap_file_name = (
            f"{self.report_folder}{os.path.sep}"
            f"{tap_report_sub_folder}{os.path.sep}"
            f"mega-linter-{self.master.name}.tap"
        )
        if not os.path.isdir(os.path.dirname(tap_file_name)):
            os.makedirs(os.path.dirname(tap_file_name), exist_ok=True)
        with open(tap_file_name, "w", encoding="utf-8") as tap_file:
            tap_file_content = "\n".join(tap_report_lines) + "\n"
            tap_file.write(tap_file_content)
            logging.info(
                f"[Tap Reporter] Generated {self.name} report: {tap_file_name}"
            )
`

**Comment by cezarfw** [comment]
![Captura de tela de 2021-04-12 19-49-16](https://user-images.githubusercontent.com/25337162/114472343-6a0e0400-9bc8-11eb-97dd-faac19d192f0.png)

**Comment by cezarfw** [comment]
POWERSHELL
![image](https://user-images.githubusercontent.com/25337162/114472410-87db6900-9bc8-11eb-9408-ca0525cb0327.png)

**Comment by nvuillam** [comment]
> Are you sure this variable rolls?
> 
> Property OUTPUT_DETAILS is not allowed.yaml-schema: https://raw.githubusercontent.com/nvuillam/mega-linter/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json
> 
> json schema does not exist, I'm passing via docker run as I mentioned earlier.

Some parts of the json schema are written manually.... and can contain errors ^^

**Comment by nvuillam** [comment]
> Some specific adjustments to the code and TAP started to be generated. Adjustments are still needed but it is a start.
> 
> ```
> """
> TAP reporter
> https://testanything.org/
> """
> import logging
> import os
> 
> from megalinter import Reporter, config, utils
> 
> 
> class TapReporter(Reporter):
>     name = "TAP"
>     scope = "linter"
> 
>     def __init__(self, params=None):
>         # report_type is tap by default
>         self.report_type = "tap"
>         super().__init__(params)
> 
>     def manage_activation(self):
>         # Super-Linter legacy variables
>         output_format = config.get("OUTPUT_FORMAT", "")
>         if output_format.startswith("tap"):
>             self.is_active = True
>             if config.get("OUTPUT_DETAIL", "") == "detailed":
>                 self.report_type = "detailed"
>         # Mega-Linter vars (false by default)
>         elif config.get("TEXT_REPORTER", "false") == "true":
>             self.is_active = True
>         else:
>             self.is_active = False
>         if self.is_active is True:
>             # If TAP is active, we must lint file by file to have result file by file in TAP
>             if self.master.cli_lint_mode == "list_of_files":
>                 self.master.cli_lint_mode = "file"
>             elif self.master.cli_lint_mode == "project":
>                 self.is_active = False
>                 logging.warning(
>                     f"Tap output is not available for {self.master.linter_name}"
>                 )
> 
>     def produce_report(self):
>         self.master.cli_lint_mode == "list_of_files"
>         tap_report_lines = ["TAP version 13",
>                             f"1..{str(len(self.master.files))}"]
>         # Convert file results in TAP
>         for index, file_result in enumerate(self.master.files_lint_results):
>             file_nm = utils.normalize_log_string(file_result["file"])
>             tap_status = "ok" if file_result["status_code"] == 0 else "not ok"
>             file_tap_lines = [f"{tap_status} {str(index + 1)} - {file_nm}"]
>             if (
>                 self.report_type == "detailed"
>                 or file_result["stdout"] != ""
>                 and file_result["status_code"] != 0
>             ):
>                 std_out_tap = (
>                     file_result["stdout"].rstrip(
>                         f" {os.linesep}") + os.linesep
>                 )
>                 std_out_tap = "\\n".join(std_out_tap.splitlines())
>                 std_out_tap = std_out_tap.replace(":", " ")
>                 detailed_lines = [
>                     "  ---", f"  message: {std_out_tap}", "  ..."]
>                 file_tap_lines += detailed_lines
>                 tap_report_lines += file_tap_lines
>         # Write TAP file
>         tap_report_sub_folder = config.get("TAP_REPORTER_SUB_FOLDER", "tap")
>         tap_file_name = (
>             f"{self.report_folder}{os.path.sep}"
>             f"{tap_report_sub_folder}{os.path.sep}"
>             f"mega-linter-{self.master.name}.tap"
>         )
>         if not os.path.isdir(os.path.dirname(tap_file_name)):
>             os.makedirs(os.path.dirname(tap_file_name), exist_ok=True)
>         with open(tap_file_name, "w", encoding="utf-8") as tap_file:
>             tap_file_content = "\n".join(tap_report_lines) + "\n"
>             tap_file.write(tap_file_content)
>             logging.info(
>                 f"[Tap Reporter] Generated {self.name} report: {tap_file_name}"
>             )
> ```

Great, maybe you'd like to make a PR ?

Powershell is a special case (use of pwsh linux package), maybe and uses a custom Linter class for execution, maybe there is something additional there to reformat output

https://github.com/nvuillam/mega-linter/blob/master/megalinter/linters/PowershellLinter.py
