### ISSUE TITLE
What's the preferred way to support multiple .mega-linter.yml configs?

### ISSUE THREAD

**Issue by ayyjohn** [nvuillam/mega-linter#416]
I have two main configurations I run my mega-linter in, 

call this one "full lint and fix". it's what I run as a pre-push
```
---
APPLY_FIXES: all
# DISABLE_LINTERS:
  # - MARKDOWN_MARKDOWN_LINK_CHECK
ENABLE:
  - MARKDOWN
  - SPELL
  - JAVASCRIPT
JAVASCRIPT_FILTER_REGEX_INCLUDE: (custom_lint_rules|js)
FILTER_REGEX_EXCLUDE: (_site/|test_posts/)
MARKDOWN_FILTER_REGEX_INCLUDE: (_posts/)
SPELL_FILTER_REGEX_INCLUDE: (_posts/)
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_MARKDOWNLINT_ARGUMENTS: -r "/tmp/lint/custom_lint_rules"
```

and this one "checkup" that I just run from time to time during writing
```
---
# APPLY_FIXES: all
DISABLE_LINTERS:
  - MARKDOWN_MARKDOWN_LINK_CHECK
ENABLE:
  - MARKDOWN
  - SPELL
  - JAVASCRIPT
JAVASCRIPT_FILTER_REGEX_INCLUDE: (custom_lint_rules|js)
FILTER_REGEX_EXCLUDE: (_site/|test_posts/)
MARKDOWN_FILTER_REGEX_INCLUDE: (_posts/)
SPELL_FILTER_REGEX_INCLUDE: (_posts/)
FLAVOR_SUGGESTIONS: false
PRINT_ALPACA: false
SHOW_ELAPSED_TIME: true
JAVASCRIPT_DEFAULT_STYLE: prettier
MARKDOWN_MARKDOWNLINT_ARGUMENTS: -r "/tmp/lint/custom_lint_rules"
```

I know that there's `--fix` that you can use with `npx mega-linter-runner` to turn on/off the `APPLY_FIXES`, but what I was hoping for was to have two `.mega-linter.yml` files and specify which one to use using, say, two aliases

`alias preflight="npx mega-linter-runner --config=".mega-linter-preflight.yml"`
`alias shortlint="npx mega-linter-runner --config=".mega-linter-short.yml"`
or something similar. I don't see how that's supported currently, if it is. 

```
npx mega-linter-runner --help
mega-linter [options]

  -r, --release String     Mega-Linter version - default: v4
  --flavor String          Mega-Linter flavor - default: all
  -p, --path path::String  Directory containing the files to lint
                           (default: current directory) - default: .
  -e, --env [String]       Environment variable (multiple)
  --fix                    Apply formatters and fixes in linted sources
  --nodockerpull           Do not pull docker image before running it
  --debug                  See debug logs
  -h, --help               Show help (mega-linter --help OPTIONNAME to
                           see option detail)
  -v, --version            Show version
  -i, --install            Generate Mega-Linter configuration in your
                           project
```
none of these seem to do what I want.

I do see that there's a `MEGALINTER_CONFIG` variable that you can put in `.mega-linter.yml` but I'm not sure if/how I could use that to accomplish this goal.

**Comment by nvuillam** [comment]
You can do that by using MEGALINTER_CONFIG as an environment variable :)

For example : 
```shell
MEGALINTER_CONFIG=.mega-linter2.yml npx mega-linter-runner
```

Such variable can also be defined in CI jobs

**Comment by ayyjohn** [comment]
OH! It's an ENV variable. That makes so much more sense. 
Awesome, Thanks @nvuillam :)

**Comment by nvuillam** [comment]
All mega-linter variables can be set as env variables :)
When a variable exists in both ENV and .mega-linter.yml, the ENV variable has the priority :)

**Comment by ayyjohn** [comment]
🤯
