### ISSUE TITLE
CWD and linter working directories

### ISSUE THREAD

**Issue by omusavi** [nvuillam/mega-linter#419]
Had a general question that might eventually lead to a PR but unsure of the logic right now so wanted to double check before submitting a fix.

I am having some issues with ESLint and mega-linter, but only when running locally. I have created a sample repo to show the error here: https://github.com/omusavi/mega-linter-eslint-bug-example

The issue is that [in Linter.py](https://github.com/nvuillam/mega-linter/blob/360e9408b748a4dc7a7a060c0fd11f7dc4c3ee6b/megalinter/Linter.py#L559), the current working directory is set as:

```python
        cwd = (
            os.getcwd()
            if self.cli_lint_mode in ["file", "list_of_files"]
            else self.workspace
        )
```

In the case of a github action, it seems like it is being set to [/github/workspace/](https://github.com/omusavi/mega-linter-eslint-bug-example/runs/2374573817?check_suite_focus=true#step:6:231), but when run locally with `mega-linter-runner`, it is set to the root of the container `/`.

This causes failures with specific usages of ESLint (like the airbnb config rules in the sample repo) that depend on the typescript config files to be relative to the working directory that is executing ESLint (see [the README in the sample repo](https://github.com/omusavi/mega-linter-eslint-bug-example/blob/main/README.md) for the exact error message). I had actually [begun work on a branch](https://github.com/omusavi/mega-linter/tree/relative-lint-paths) to fix this with relative links for files before realizing this was a local-only issue and now I feel like the fix is too big. 

Instead of adding a new `cli_lint_mode`, a smaller and simpler fix would be to always just set the `cwd` to `self.workspace`, but I don't fully understand what cases we would not want that. Any insights or ideas on how to solve this would be helpful!

**Comment by omusavi** [comment]
@nvuillam thoughts on this question?

**Comment by nvuillam** [comment]
@omusavi did you PR solve the issue ?
