### ISSUE TITLE
`*_FILE_NAMES_REGEX` only examines the file name and doesn't include the extension

### ISSUE THREAD

**Issue by ottumm** [nvuillam/mega-linter#445]
**Describe the bug**
When setting e.g. `BASH_SHELLCHECK_FILE_NAMES_REGEX`, it only looks at the file name and not the extension, even if an extension is present. I would like to be able to tell Mega-Linter to check the file `foo` as a Bash file, but not `foo.py`. This doesn't appear to be possible with the current implementation.

**To Reproduce**
I've created a branch that demonstrates this behavior. See https://github.com/ottumm/mega-linter-test/pull/2

You can see ShellCheck attempting to check a `.py` file here: https://github.com/ottumm/mega-linter-test/pull/2/checks?check_run_id=2530002709#step:4:133

**Expected behavior**
`*_FILE_NAMES_REGEX` should use the entire filename, including extension, when evaluating, so that I can use e.g. `BASH_SHELLCHECK_FILE_NAMES_REGEX: ["^foo$"]` to match the file `foo` and not the file `foo.py`.

**Comment by nvuillam** [comment]
That's a legitimate request, thanks for asking :)
I'll do that when I have some time, or maybe someone wants to make a PR ? :)

**Comment by ottumm** [comment]
I'm happy to take a shot at a PR!

**Comment by ottumm** [comment]
I read the intention of the `*_FILE_NAMES_REGEX` setting to only potentially match files that do not have an extension (e.g. `Dockerfile`, `Jenkinsfile`). Is that accurate?

**Comment by ottumm** [comment]
@nvuillam when do you expect to cut a release that includes this fix? It's not ultra urgent on my end but sooner would be helpful for me.

**Comment by nvuillam** [comment]
I can do that today :)
