### ISSUE TITLE
Malformed configuration table in Markdown docs

### ISSUE THREAD

**Issue by tpansino** [nvuillam/mega-linter#446]
**Describe the bug**
The configuration table in the Markdown documentation for each linter has some malformed JSON which is causing the `Description` text to appear in the `Default Value` cell.

This seems to be an issue on most, if not all of these docs for each linter. I'm guessing these are generated from a template and the template just needs to be fixed.

**To Reproduce**
See screenshot and link below.

**Expected behavior**
`lib)` should be in the `Description` column.

**Screenshots**

Screenshot of just [one affected page](https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/spell_cspell.md#configuration-in-mega-linter):

![image](https://user-images.githubusercontent.com/2768420/117511133-1af68d00-af42-11eb-8d32-2fcb0002f439.png)

**Additional context**

**Comment by tpansino** [comment]
I think the fix would just be to escape the pipe `|` like so:

`Custom regex excluding filter<br/>Ex: `(test\|examples)`

**Comment by nvuillam** [comment]
That seems to be the good solution, thanks ! :)
Would you be ok to make a PR ? ( it's in build.by -> https://github.com/nvuillam/mega-linter/blob/5171b4ca79b500edd7f45514329595f9e4816032/.automation/build.py#L751 )
