### ISSUE TITLE
New Linter suggestion: `terraform fmt`

### ISSUE THREAD

**Issue by tpansino** [nvuillam/mega-linter#447]
**Is your feature request related to a problem? Please describe.**
The current linter suite includes a call to `terragrunt hclfmt`, but this only formats Terragrunt HCL syntax files, not standard Terraform files.

**Describe the solution you'd like**
A very similar linter that calls `terraform fmt` on relevant files seems appropriate.

**Describe alternatives you've considered**
None

**Additional context**
I'd be happy to contribute this, but I wanted to first check with the maintainers (@nvuillam).

I'm also unsure of the name. The existing pattern of `TERRAFORM_TERRAGRUNT` would lead me to `TERRAFORM_TERRAFORM`, but they both should really be something more like `TERRAFORM_TERRAGRUNT_HCLFMT` and `TERRAFORM_TERRAFORM_FMT`.

**Comment by nvuillam** [comment]
That's a great proposition, please be my guest to make the PR and don't hesitate to ask me for support :)
