### ISSUE TITLE
Add support for Checkov Terraform linter

### ISSUE THREAD

**Issue by tpansino** [nvuillam/mega-linter#459]
**Is your feature request related to a problem? Please describe.**
The Terrascan linter [documentation](https://docs.accurics.com/projects/accurics-terrascan/en/latest/policies/aws/) for checks is very limited, which makes it difficult to determine (1) the reason a check is failing and (2) what actions can be taken to fix the issue. Its waiver system is also very hard to use.

**Describe the solution you'd like**
[Checkov](https://checkov.io) is a similar Terraform static analysis/linting tool, but with somewhat better documentation of lint checks and examples of fixes that can be made. It also has a very easy to use waiver system via comments on individual Terraform resources.

**Describe alternatives you've considered**

**Additional context**
I'd like to contribute this to Mega-Linter, assuming having two linters that do approximately the same thing is acceptable.

**Comment by nvuillam** [comment]
@tpansino there is no problem to have several linters for the same language/format (it's already the case for Mega-Linter python linters for example), so you are very welcome to make a PR :)

**Comment by tpansino** [comment]
Still working on this, just haven't had time to finish up the PR yet.

**Comment by nvuillam** [comment]
@tpansino that's good news :)
