### ISSUE TITLE
Use of DOCKERFILE_FILTER_REGEX_INCLUDE

### ISSUE THREAD

**Issue by Fred-MabS** [nvuillam/mega-linter#502]
Hi,

I have several Dockerfiles:
```
$ ls Dock*
Dockerfile		Dockerfile.both		Dockerfile.runner	Dockerfile_base
```

I want all of them to be linted, and thus I have declared:
`DOCKERFILE_FILTER_REGEX_INCLUDE: 'Dockerfile(.*)'`

However, only `Dockerfile` is processed:
```
+----SUMMARY----+----------------+-------+-------+--------+--------------+
| Descriptor    | Linter         | Files | Fixed | Errors | Elapsed time |
+---------------+----------------+-------+-------+--------+--------------+
| ✅ DOCKERFILE | dockerfilelint |     1 |       |      0 |        1.27s |
+---------------+----------------+-------+-------+--------+--------------+
```

I have tried with:
`DOCKERFILE_FILTER_REGEX_INCLUDE: 'Dockerfile_base'`
It should match an other file but instead no file is processed.

Do I miss something on the use of this variable?

As side note, I have checked my regexp with this short code which prints all the files that are supposed to be processed:
```
import os
import re

file_contains_regex = 'Dockerfile(.*)'
for _, _, filenames in os.walk('.'):
    file_contains_regex_object = re.compile(file_contains_regex, flags=re.MULTILINE)
    for filename in filenames:
        if file_contains_regex_object.search(filename):
            print(f'{filename}')
```

Best regards,
Fred

**Comment by nvuillam** [comment]
FILTER_REGEX_INCLUDE is for general file browsing

In the case of some linters where there are file names defined, there is another variable than you can use: DOCKERFILE_DOCKERFILELINT_FILE_NAMES_REGEX

https://nvuillam.github.io/mega-linter/descriptors/dockerfile_dockerfilelint/#configuration-in-mega-linter

Please could you remove the INCLUDE filter and try with the following

```yaml
DOCKERFILE_DOCKERFILELINT_FILE_NAMES_REGEX: ["Dockerfile(-.+)?]
```

**Comment by Fred-MabS** [comment]
Thank you, it now works with:

`DOCKERFILE_DOCKERFILELINT_FILE_NAMES_REGEX: ["Dockerfile(.*)"]`
