### ISSUE TITLE
Enable mega-linter-runner to pull from alternative container registry address

### ISSUE THREAD

**Issue by bcdady** [nvuillam/mega-linter#564]
**Is your feature request related to a problem? Please describe.**
Currently, mega-linter-runner only pulls Docker container images directly and only from [hub.docker.com](https://hub.docker.com)

**Describe the solution you'd like**
mega-linter-runner could be updated to use a specified, configured container registry address.

**Additional context**
This isn't a problem when run in a CI system (like GitLab or GitHub Actions), as those systems already provide means to specify alternative container registries.

**Comment by nvuillam** [comment]
Main Mega-Linter image is also deployed on GitHub Container Registry, but Flavor images are not (I don't remember why but it should not be hard to do)

No problem to update mega-linter-runner so it can call any registry or even any image, I'll do that asap :)
Do you have a specific requirement ? What is the case it will solve for you ?

**Comment by bcdady** [comment]
My use case will be to pull the image from an Nexus repository proxy in our development network.

**Comment by nvuillam** [comment]
@bcdady it should work now :)

Please can you try something like `npx mega-linter-runner --image your-registry.com/mega-linter-python:v4` and confirm me that it solves your case  ?
