### ISSUE TITLE
Support @generated markers

### ISSUE THREAD

**Issue by stepancheg** [nvuillam/mega-linter#579]
Ignore files marked with `@generated` marker.

As described here: https://generated.at/

**Comment by nvuillam** [comment]
@stepancheg in progress :)

**Comment by stepancheg** [comment]
Thanks!

**Comment by nvuillam** [comment]
@stepancheg > it is delivered in latest/insiders version, you can already use it, or wait some day for a new official release :)

**Comment by stepancheg** [comment]
clang-format linter #478 would be probably good enough reason to switch some project from super-linter to mega-linter. (But I'm not the owner of that project, so I could only create a PR for them).

**Comment by nvuillam** [comment]
There are already [other reasons](https://nvuillam.github.io/mega-linter/mega-linter-vs-super-linter/) , but it's true that they recently added clang-format and that it's not the case here yet ^^ 

If don't think i'll have a lot of time to make the PR before this week-end (rent-paying job is very time consuming), if you feel it you can try, i'll be glad to accept the PR :)
