### ISSUE TITLE
Detached head state in git after running MegaLinter

### ISSUE THREAD

**Issue by TimPansino** [nvuillam/mega-linter#604]
**Describe the bug**
Running megalinter locally causes repo to end up in detached head state.

**To Reproduce**

1. `git status` -> `On branch feature-linting`
1. `mega-linter -f python --fix` -> Run to completion
1. `git status` -> `HEAD detached at dd492c19c`

**Expected behavior**
After running, repo should be on the same branch it started on.

**Screenshots**
N/A

**Additional context**
Megalinter logs show a warning, possibly related.

```
Listing updated files in [/tmp/lint] using git diff, then filter with:
Warning: Unable to pull current branch dd492c19c92ff5d4c74ae5659e36d82c45ef4eb8
Git diff :
.github/workflows/mega-linter.yml
.gitignore
.mega-linter.yml
pyproject.toml
setup.cfg
tests/framework_graphene/_target_application.py
```

My config file

```
APPLY_FIXES: none # all, none, or list of linter keys
DEFAULT_BRANCH: main # Usually master or main
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
VALIDATE_ALL_CODEBASE: false
ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
  - MARKDOWN_MARKDOWN_LINK_CHECK
  - MARKDOWN_MARKDOWNLINT
  - PYTHON_BANDIT
  - PYTHON_BLACK
  - PYTHON_FLAKE8
  - PYTHON_ISORT
  - PYTHON_PYLINT
  - RST_RST_LINT
  - RST_RSTCHECK
  - RST_RSTFMT
  - YAML_PRETTIER
  - YAML_V8R
  - YAML_YAMLLINT
```

Full logs attached

[mega-linter.log](https://github.com/nvuillam/mega-linter/files/6909337/mega-linter.log)

I also noticed when I run it with `IGNORE_GITIGNORED_FILES: true` I get a different error as well, could also be related. Looks like an iterable was expected here but a string was passed.

```
Warning: Unable to pull current branch 5468884b48d22c777537da5391ed835ad1b11bc3
Git diff :
.github/workflows/mega-linter.yml
.gitignore
.mega-linter.yml
pyproject.toml
setup.cfg
tests/framework_graphene/_target_application.py
- File extensions: .md, .py, .rst, .yaml, .yml
Unable to list git ignored files (Cmd('g') not found due to: FileNotFoundError('[Errno 2] No such file or directory: 'git status --ignored'')
  cmdline: g i t   s t a t u s   - - i g n o r e d)
```

**Comment by MikolajBalcerek** [comment]
My workaround for convenience is to use a Makefile as a wrapper instead of the provided `mega-linter`:

```
BRANCH := $(shell git rev-parse --abbrev-ref HEAD)

CURRENT_UID := $(shell id -u)
CURRENT_GID := $(shell id -g)

mega-lint:
	-docker run  -v ${PWD}:/tmp/lint --user ${CURRENT_UID}:${CURRENT_GID} nvuillam/mega-linter:v4
	git checkout -m ${BRANCH} # return to your original branch after linting for convenience, instead of last commit HEAD

mega-lint-fix:
	-docker run  -e APPLY_FIXES=all " -v ${PWD}:/tmp/lint --user ${CURRENT_UID}:${CURRENT_GID} nvuillam/mega-linter:v4
	git checkout -m ${BRANCH} # return to your original branch after linting for convenience, instead of last commit HEAD
```

**Comment by nvuillam** [comment]
Thanks for the workaround @MikolajBalcerek , we can to use that solve the Mega-Linter issue, so it would not be necessary anymore ^^

@tpansino > the IGNORE_GITIGNORED_FILES seems to be another bug indeed. Interested to do a PR ? 👼

**Comment by nvuillam** [comment]
Hmmm I've lost the track a little ... what is not solved yet about this issue ? :/

**Comment by noskovao** [comment]
This issue still exists when you set **VALIDATE_ALL_CODEBASE=false**. Checked on the latest image today.
Moreover, it is converting files to DOS format during the linting which cause false-positive errors from prettier:
```[prettier] .groovylintrc.json - ERROR - 1 error(s)
--Error detail:
Checking formatting...
[warn] tmp/lint/.groovylintrc.json
[warn] Code style issues found in the above file(s). Forgot to run Prettier?
```

```
diff --git a/.groovylintrc.json b/.groovylintrc.json
index 797998e7..8126abc7 100644
--- a/.groovylintrc.json
+++ b/.groovylintrc.json
@@ -1,17 +1,17 @@
-{
-    "extends": "recommended",
-    "rules": {
-        "CompileStatic": {
-            "enabled": false
-        },
-        "DuplicateNumberLiteral": {
-            "enabled": false
-        },
-        "DuplicateStringLiteral": {
-            "enabled": false
-        },
-        "NestedBlockDepth": {
-            "enabled": false
-        }
-    }
+{^M
+    "extends": "recommended",^M
+    "rules": {^M
+        "CompileStatic": {^M
+            "enabled": false^M
+        },^M
+        "DuplicateNumberLiteral": {^M
+            "enabled": false^M
+        },^M
+        "DuplicateStringLiteral": {^M
+            "enabled": false^M
+        },^M
+        "NestedBlockDepth": {^M
+            "enabled": false^M
+        }^M
+    }^M
```

**Comment by noskovao** [comment]
I've created the draft PR with an idea of how to fix this and other issues mentioned in this ticket.
Please take a look https://github.com/nvuillam/mega-linter/pull/760/commits/33b86c85c7d18c7b9619f94e439f4662286e44f7
For some reason after execution of "repo.git.checkout(current_branch)" with "autocrlf = true" git global config, files become  DOS formated.
I've tested these changes and it works fine, returning exact diff list,  no checkout, no DOS formatted files.
If it is OK and doesn't affect any other part of the code, I can adjust the commit to remove unused variables across the project and push it for the final review.
