### ISSUE TITLE
JSON Schema out-of-date

### ISSUE THREAD

**Issue by lars-reimann** [nvuillam/mega-linter#615]
**Describe the bug**
The [JSON schema](https://nvuillam.github.io/mega-linter/json-schemas/configuration.html) seems to be missing some options that are mentioned in the documentation.

* ENABLED_LINTERS/DISABLED_LINTERS:
  * GO_REVIVE
  * PYTHON_BANDIT
  * PYTHON_MYPY
  * SALESFORCE_SFDX_SCANNER_APEX
  * SALESFORCE_SFDX_SCANNER_AURA
  * SALESFORCE_SFDX_SCANNER_LWC
  * SQL_SQLFLUFF
  * SWIFT_SWIFTLINT
  * JSON_PRETTIER
  * MARKDOWN_MARKDOWN_TABLE_FORMATTER
  * YAML_PRETTIER
  * TERRAFORM_TERRAFORM_FMT
  * TERRAFORM_CHECKOV

* Common variables:
  * IGNORE_GENERATED_FILES
  * MEGALINTER_CONFIG

I checked all linters and all common variables but none of the other parts of the schema.

**To Reproduce**

1. Compare [configuration docs](https://nvuillam.github.io/mega-linter/configuration/) with [JSON schema](https://nvuillam.github.io/mega-linter/json-schemas/configuration.html)
2. Compare [linter list in docs](https://nvuillam.github.io/mega-linter/supported-linters/) with [JSON schema](https://nvuillam.github.io/mega-linter/json-schemas/configuration.html#DISABLE_LINTERS_items)

**Expected behavior**
Docs and schema should match.

**Screenshots**

![image](https://user-images.githubusercontent.com/2501322/128244535-a62bd95f-07f7-4f70-add3-8aa453495a29.png)

**Additional context**
I just want to say thanks for a very promising and useful tool.

**Comment by nvuillam** [comment]
@lars-reimann  > That's true for IGNORE_GENERATED_FILE that I forgot (PR in progress), but for the linters you identified, they are part of JSON schema (which is mostly generated automatically from linter descriptors)

![image](https://user-images.githubusercontent.com/17500430/128339792-0bda362f-745b-4768-b2e8-c5010f05e32f.png)

What IDE do you use ? It seems the used JSON schema is out of date :/

**Comment by lars-reimann** [comment]
That's curious. The current state for me is:
* [website](https://nvuillam.github.io/mega-linter/json-schemas/configuration.html#DISABLE_LINTERS_items) is up-to-date
* works in VS code
* does **not** work in IntelliJ (which I was using initially), even after clearing caches. It seems to point to [the correct schema](https://raw.githubusercontent.com/nvuillam/mega-linter/master/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json) but still shows warnings. But that no longer seems to be an issue with mega-linter.

**Comment by lars-reimann** [comment]
@nvuillam IntelliJ seems to be using this section the schema, which is indeed missing these keys.

```
  "description": "Mega-Linter configuration file",
  "enum_linter_keys": {
    "enum": [
      "ANSIBLE_ANSIBLE_LINT",
      "ARM_ARM_TTK",
      "BASH_EXEC",
      "BASH_SHELLCHECK",
      "BASH_SHFMT",
      "C_CPPLINT",
      "CLOJURE_CLJ_KONDO",
      "CLOUDFORMATION_CFN_LINT",
      "COFFEE_COFFEELINT",
      "COPYPASTE_JSCPD",
      "CPP_CPPLINT",
      "CSHARP_DOTNET_FORMAT",
      "CSS_STYLELINT",
      "CSS_SCSS_LINT",
      "DART_DARTANALYZER",
      "DOCKERFILE_DOCKERFILELINT",
      "DOCKERFILE_HADOLINT",
      "EDITORCONFIG_EDITORCONFIG_CHECKER",
      "ENV_DOTENV_LINTER",
      "GHERKIN_GHERKIN_LINT",
      "GIT_GIT_DIFF",
      "GO_GOLANGCI_LINT",
      "GRAPHQL_GRAPHQL_SCHEMA_LINTER",
      "GROOVY_NPM_GROOVY_LINT",
      "HTML_HTMLHINT",
      "JAVA_CHECKSTYLE",
      "JAVASCRIPT_ES",
      "JAVASCRIPT_STANDARD",
      "JAVASCRIPT_PRETTIER",
      "JSON_JSONLINT",
      "JSON_ESLINT_PLUGIN_JSONC",
      "JSON_V8R",
      "JSX_ESLINT",
      "KOTLIN_KTLINT",
      "KUBERNETES_KUBEVAL",
      "LATEX_CHKTEX",
      "LUA_LUACHECK",
      "MARKDOWN_MARKDOWNLINT",
      "MARKDOWN_REMARK_LINT",
      "MARKDOWN_MARKDOWN_LINK_CHECK",
      "OPENAPI_SPECTRAL",
      "PERL_PERLCRITIC",
      "PHP_BUILTIN",
      "PHP_PHPCS",
      "PHP_PHPSTAN",
      "PHP_PSALM",
      "POWERSHELL_POWERSHELL",
      "PROTOBUF_PROTOLINT",
      "PUPPET_PUPPET_LINT",
      "PYTHON_PYLINT",
      "PYTHON_BLACK",
      "PYTHON_FLAKE8",
      "PYTHON_ISORT",
      "R_LINTR",
      "RAKU_RAKU",
      "RST_RST_LINT",
      "RST_RSTCHECK",
      "RST_RSTFMT",
      "RUBY_RUBOCOP",
      "RUST_CLIPPY",
      "SALESFORCE_SFDX_SCANNER",
      "SCALA_SCALAFIX",
      "SNAKEMAKE_LINT",
      "SNAKEMAKE_SNAKEFMT",
      "SPELL_MISSPELL",
      "SPELL_CSPELL",
      "SQL_SQL_LINT",
      "TEKTON_TEKTON_LINT",
      "TERRAFORM_TFLINT",
      "TERRAFORM_TERRASCAN",
      "TERRAFORM_TERRAGRUNT",
      "TSX_ESLINT",
      "TYPESCRIPT_ES",
      "TYPESCRIPT_STANDARD",
      "TYPESCRIPT_PRETTIER",
      "VBDOTNET_DOTNET_FORMAT",
      "XML_XMLLINT",
      "YAML_YAMLLINT",
      "YAML_V8R"
    ],
    "type": "string"
  },
```

**Comment by nvuillam** [comment]
Those keys are not missing in master version of the schema ^^ 

https://github.com/nvuillam/mega-linter/blob/b4761190ddb97fcac8070473b878a067bccc91e3/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json#L100

From where is your JSON sample ? it does not contain `MARKDOWN_MARKDOWN_TABLE_FORMATTER` whereas it is available in Mega-Linter repo ->

![image](https://user-images.githubusercontent.com/17500430/128350585-2ac4a022-16a6-417e-ae9b-59bf3ec60837.png)

**Comment by lars-reimann** [comment]
@nvuillam Unless I have some really weird caching issues on my side, they are missing, though. **It's a different location than you pointed to**. See
 https://github.com/nvuillam/mega-linter/blob/b4761190ddb97fcac8070473b878a067bccc91e3/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json#L239. 

I think there might be some unintended duplication in the schema.

**Comment by nvuillam** [comment]
I just clicked on your hyperlink and saw markdown table formatter entry, do you see it on your link ? ![Screenshot_20210805-145021.png](https://user-images.githubusercontent.com/17500430/128352782-2bcd6755-e735-4470-b1ea-ba5832fb5ec3.png)

**Comment by lars-reimann** [comment]
In line 144, yes. In line 239, where I pointed to, no. The entire part "enum_linter_keys" is defined twice:

https://github.com/nvuillam/mega-linter/blob/b4761190ddb97fcac8070473b878a067bccc91e3/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json#L100

https://github.com/nvuillam/mega-linter/blob/b4761190ddb97fcac8070473b878a067bccc91e3/megalinter/descriptors/schemas/megalinter-configuration.jsonschema.json#L198

**Comment by nvuillam** [comment]
You're totally right, enum_linter_keys should be only within `definitions` :)
Thanks for the PR !
