### ISSUE TITLE
Request a new mega linter flavor - Clojure

### ISSUE THREAD

**Issue by evg-tso** [nvuillam/mega-linter#623]
[Clojure](https://clojure.org/) is hosted on the JVM.  
I'd like to either add it to the [java flavor](https://github.com/nvuillam/mega-linter/blob/master/docs/flavors/java.md) or create a duplicate of it, replacing Kotlin with Java.  

What do you think?

**Comment by nvuillam** [comment]
As Clojure is JVM based, it would have its place in java flavor yep :)

**Comment by evg-tso** [comment]
Should I create a PR and update the [java flavor](https://github.com/nvuillam/mega-linter/blob/master/flavors/java/flavor.json)?

**Comment by nvuillam** [comment]
@evg-tso I didn't see your message, I just created #626 :)
