### ISSUE TITLE
How to add new linter in mega-linter? 

### ISSUE THREAD

**Issue by lokk3d** [nvuillam/mega-linter#663]
Hi, i'm trying to add this tool for static analysis of a solidity code:
https://github.com/crytic/slither

How can i add a new linter to the already existing ones?

It would be really helpful to me!

**Comment by nvuillam** [comment]
Hi @lokk3d , instructions to add a new linter and make a PR are here :) -> https://nvuillam.github.io/mega-linter/contributing/#add-a-new-linter

Don't ask hesitate to ask questions if anything is not clear :)

**Comment by lokk3d** [comment]
Really thanks, i'll try to integrate it! 

Does mega-linter offers also a cyclomatic analysis through linters? I think it could be a really great feature!

**Comment by nvuillam** [comment]
it does... when the linter embeds rules about cyclomatic complexity , so when the linter does, Mega-Linter does :)
