### ISSUE TITLE
Cosmetic - New Line Feed missing in ERROR-MARKDOWN_MARKDOWN_TABLE_FORMATTER.log 

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#665]
**Describe the bug**
New Line Feed missing in `ERROR-MARKDOWN_MARKDOWN_TABLE_FORMATTER.log` 

**To Reproduce**

1. Run  `docker run -v $(pwd):/tmp/lint nvuillam/mega-linter-php:v4 mega-linter-runner --flavor php`

**Expected behavior**
A new line before to print the bullet list **tables to format**

**Screenshots**

<details>
<summary>ERROR-MARKDOWN_MARKDOWN_TABLE_FORMATTER.log</summary>

```
Results of markdown-table-formatter linter (version 1.1.0)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/markdown_markdown_table_formatter/
-----------------------------------------------

❌ [ERROR] for workspace /tmp/lint
Linter raw log:
2 files contain markdown tables to format: - 
/tmp/lint/README.md
- /tmp/lint/ROADMAP.md
```

</details>

**Comment by nvuillam** [comment]
The error is not related to Mega-Linter but to [markdown-table-formatter](https://github.com/nvuillam/markdown-table-formatter)

Fortunately, I am also the author if markdown-table-formatter so I'll take a look :)

**Comment by nvuillam** [comment]
New version of markdown-lable-formatter has been released and will be catched by Mega-Linter Auto-Update CI job in some dozens of minutes :)

**Comment by nvuillam** [comment]
Solved and integrated in latest / insiders version of Mega-Linter :)

**Comment by llaville** [comment]
Confirmed with command `docker run -v $(pwd):/tmp/lint nvuillam/mega-linter-php:latest mega-linter-runner --flavor php`

and report log

```

Results of markdown-table-formatter linter (version 1.2.0)
See documentation on https://nvuillam.github.io/mega-linter/descriptors/markdown_markdown_table_formatter/
-----------------------------------------------

❌ [ERROR] for workspace /tmp/lint
Linter raw log:
2 files contain markdown tables to format:
- /tmp/lint/README.md
- /tmp/lint/ROADMAP.md

```
