### ISSUE TITLE
Typo errors in README activation-and-deactivation section

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#667]
**Describe the bug**
Typo error in PHP linter names

**Expected behavior**

<blockquote>
- Run all linters except PHP linters (PHP_BUILTIN, PHP_PHPCS, PHP_PHPSTAN, PHP_PSALM)

```yaml
DISABLE: PHP
```

- Run all linters except PHP_PHPSTAN and PHP_PSALM linters

```yaml
DISABLE_LINTERS: PHP_PHPSTAN,PHP_PSALM
```

</blockquote>

**Screenshots**

https://github.com/nvuillam/mega-linter/blob/master/README.md#activation-and-deactivation

<blockquote>
- Run all linters except PHP linters (PHP_BUILTIN, PHP_PCPCS, PHP_STAN, PHP_PSALM)

```yaml
DISABLE: PHP
```

- Run all linters except PHP_STAN and PHP_PSALM linters

```yaml
DISABLE_LINTERS: PHP_STAN,PHP_PSALM
```

</blockquote>

**Comment by nvuillam** [comment]
Indeed ^^

Maybe you'd like to make a PR ? :)

**Comment by llaville** [comment]
Later, if you'd be please. I've lot of other tests to do and finish today. PR will come tomorrow.
