### ISSUE TITLE
Support for `docstrfmt` (fork of `rstfmt`)

### ISSUE THREAD

**Issue by tpansino** [nvuillam/mega-linter#670]
**Is your feature request related to a problem? Please describe.**
`rstfmt` seems dead. For example, the latest install is broken due to the release of `sphinx >= 4.0`, which has been out for some time, and the maintainer isn't showing much interest in fixing it. I previously contributed a [hack](https://github.com/nvuillam/mega-linter/blob/948609215093601125e3229723d11646c0726443/megalinter/descriptors/rst.megalinter-descriptor.yml#L50) to MegaLinter to work around this.

**Describe the solution you'd like**
[Here](https://github.com/LilSpazJoekp/docstrfmt) is a promising fork of the tool called `docstrfmt` that shows signs of recent activity, and actually works on install. I might try to contribute this as an alternative to `rstfmt`, copying the pattern used for the JavaScript and Markdown formatters to let users choose.

Or I could just replace `rstfmt` with this, since it's a fork and looks to be compatible. I'll let @nvuillam decide :)

**Describe alternatives you've considered**
Google searches don't indicate any other tools for formatting of reStructuredText. This seems to be the only real attempt at one.

**Additional context**
None

**Comment by nvuillam** [comment]
Go ! :)

**Comment by tpansino** [comment]
@TimPansino, here's one of the feature enhancements I mentioned tonight. You might be able to have a go at this since it'd be useful to the Python community. I think the new tool should be drop-in replaceable since it's a fork.
