### ISSUE TITLE
Upgrade out of date Black to a version supporting Python 3.9 to avoid it erroring out

### ISSUE THREAD

**Issue by CAM-Gerlach** [nvuillam/mega-linter#681]
**Is your feature request related to a problem? Please describe.**

Currently, our code supports Python 3.7-3.9, the last of which has been out for almost a year now. Accordingly, I specify target versions from 3.7 through 3.9 in my Black config, i.e. `target-version = ["py37", "py38", "py39"]`. However, given the Black release, 20.8, is over a year old and is the last to not support Python 3.9 released a couple months later, Black errors out on every file due to not recognizing the `target-version` key, and thus rendering it unusable for me through Mega-Linter.

**Describe the solution you'd like**

Upgrade Black to a version >=21.4 that supports Python 3.9; preferably the latest version that fixes issues with the soon to be default `experimental-string-processing` that many projects are using in production now, as well as other issues.

**Describe alternatives you've considered**

Don't upgrade Black; which will block support for language versions newer than Python 3.8, as well as not take advantage of the latest features and bug fixes.

**Additional context**

Thanks!

**Comment by nvuillam** [comment]
Released in latest/insiders, please can you confirm that it's ok now ?

Note: this [CI job](https://github.com/nvuillam/mega-linter/runs/3404311592?check_suite_focus=true) must be completed before testing is available with latest/insiders tag

**Comment by CAM-Gerlach** [comment]
Hey @nvuillam , thanks for your quick work on this! Unfortunately it doesn't seem to have worked, though its quite possible I did something wrong. I set the action to `uses: nvuillam/mega-linter@insiders` as the Readme instructs, and I could see in the build output that the latest builds were getting pulled and I verified #680 is now fixed. However, the version of Black is still shown as `- Using [black v20.8] https://black.readthedocs.io/en/stable/` and I consequently get the same error on every file.

You can check out what I have so far on r-spacex/submanager#11 ... Let me know if there's something else I should try. Thanks!

**Comment by CAM-Gerlach** [comment]
Hey @nvuillam thanks for working on this. Any updates, or anything else you need from me? Thanks!

**Comment by nvuillam** [comment]
@CAM-Gerlach now [black](https://nvuillam.github.io/mega-linter/descriptors/python_black/) version is 21.9 in Mega-Linter, is it ok ?

**Comment by CAM-Gerlach** [comment]
Sorry for the delay; put this in my to-do list and it dropped off the radar somehow. Per testing in r-spacex/submanager#11 , this does upgrade black and fix the issue, thanks. Seems like #679 is still pending, at least in the released build I tested. Thanks @nvuillam !

**Comment by CAM-Gerlach** [comment]
Of course, now Python 3.10 was just released, we'll have to do this again soon, heh.
