### ISSUE TITLE
Is FILEIO config still supported?

### ISSUE THREAD

**Issue by bcdady** [nvuillam/mega-linter#686]
We've never used the FILEIO feature, but we have `FILEIO_REPORTER: false` configured in our template .mega-linter.yml file.

So I went to review the current/latest supported configurations [here](https://nvuillam.github.io/mega-linter/configuration/), and I don't see FILEIO mentioned anymore, nor could I find any specific matches in Blame or History.

**Comment by nvuillam** [comment]
It is still here, I just reorganized the documentation to describe reporters variables on reporters doc page :)

https://nvuillam.github.io/mega-linter/reporters/

https://nvuillam.github.io/mega-linter/reporters/FileIoReporter/
