### ISSUE TITLE
Error with "Property `KUBERNETES_DIRECTORY` is not allowed" `.mega-linter.yml` (yaml-schema)

### ISSUE THREAD

**Issue by calexandre** [nvuillam/mega-linter#688]
**Describe the bug**
When using the `KUBERNETES_KUBEVAL` linter, [the documentation states](https://nvuillam.github.io/mega-linter/descriptors/kubernetes_kubeval/#configuration-in-mega-linter) that the correct way to specify the kubernetes directory is by setting the property `KUBERNETES_DIRECTORY` - but that property fails the yaml schema validation.

According the schema, the correct one would be `KUBERNETES_KUBEVAL_DIRECTORY`, and despite being valid from a schema pov, it results in nothing because the property is not recognized/used.

I believe this is just a schema issue. It needs to be changed to match the documentation and avoid the validation error.

The screenshot below demonstrates this issue:

![image](https://user-images.githubusercontent.com/1485193/130649095-0ad8d607-62a0-4fb2-91a4-4960c8964bc9.png)

**Comment by nvuillam** [comment]
Is the variable KUBERNETES_DIRECTORY taken in account when set, despite it's not in the JSON schema ?

**Comment by calexandre** [comment]
yes, it works okay if you set the `KUBERNETES_DIRECTORY` variable.

**Comment by nvuillam** [comment]
Great, i'll just have to fix the json schema:)
Or maybe u'd like to make a PR ? :)

**Comment by nvuillam** [comment]
Is it better now ? :)
