### ISSUE TITLE
Request new Mega-Linter flavor

### ISSUE THREAD

**Issue by chheanpisethpanha** [nvuillam/mega-linter#719]
Mega-Linter would run faster on my project if I had a flavor containing the following list of linters:

PYTHON_BLACK, PYTHON_FLAKE8, PYTHON_BANDIT, BASH_EXEC, BASH_SHELLCHECK, BASH_SHFMT, COPYPASTE_JSCPD, CSS_STYLELINT, DOCKERFILE_DOCKERFILELINT, DOCKERFILE_HADOLINT, GIT_GIT_DIFF, HTML_HTMLHINT, JAVASCRIPT_ES, JAVASCRIPT_PRETTIER, MARKDOWN_MARKDOWNLINT, MARKDOWN_MARKDOWN_TABLE_FORMATTER, TSX_ESLINT, TYPESCRIPT_ES, TYPESCRIPT_PRETTIER

Would it be possible to create one ? Thanks :relaxed:

PS/FYI: I'm running on WSL2

**Comment by nvuillam** [comment]
Each new flavor means additional CI Time and maintenance, I can not create an infinity of them :)

So... yes, it's possible to create one, but please can you explain what type of projects require such association of linters ?

Basically, you need to convince that you will not be the only one to use such flavor 😃

**Comment by chheanpisethpanha** [comment]
I think for our project, we are doing closed source so I'm not sure whether it's possible to be usable by everyone. I just post the suggestion from the mega linter command itself. 

Maybe I'll close this one, but I do have one question, I have a considerably high linting time on WSL2, do you have any suggestions to improve that? Thank you in advance!

```
✅ Linted [PYTHON] files with [black] successfully - (328.77s)
[Text Reporter] Generated TEXT report: /app/report/linters_logs/SUCCESS-PYTHON_BLACK.log
```

**Comment by nvuillam** [comment]
About perfs, please could you add `LOG_LEVEL: DEBUG` and share the full log ? ( privately if you prefer)

But I suspect that as we call black for each python file, it could explain the awful performances ...

I'm very busy with my paid job, please can you try to call black with a list of files, and confirm it works ?

ex: black myfile1.py myfile2.py myfile3.py

- If it works, we can add cli_mint_mode: list_of_files in [black descriptor](https://github.com/nvuillam/mega-linter/blob/40d92027923c2e2e772c6f5cb989a3b7f5954603/megalinter/descriptors/python.megalinter-descriptor.yml#L45) and i'm sure it will imprive the perfs x10 :)

- If it does not work, we could use the lint mode "projet" and call black at the root, but it wouldn't fit with Mega-Linter capability to lint only updated files, so I would need to make some architecture enhancements

**Comment by nvuillam** [comment]
@chheanpisethpanha Performances with black has dramatically improved :)

For own mega-linter linting, with other enhancements we went from 7mn to 4mn :)

It's published within latest/insiders version, and I'll release that in an official release in the next days :)
