### ISSUE TITLE
Add ssh client package for SSH based repositories

### ISSUE THREAD

**Issue by noskovao** [nvuillam/mega-linter#727]
**Describe the bug**
In the case of using mega-linter docker image locally with repositories cloned via SSH we are getting the following warning:
`Warning: Unable to pull current branch 3a806e0660119b539266860bee9206ee387b2fa4
`
Dig into the code and found the original message:
`line 1: ssh: not found`
Full Pdb log:
```
-> repo.git.pull()
(Pdb) l
483  	        current_branch = config.get("GITHUB_SHA", "")
484  	        pdb.set_trace()
485  	        if current_branch == "":
486  	            current_branch = repo.active_branch.commit.hexsha
487  	        try:
488  ->	            repo.git.pull()
489  	        except git.GitCommandError:
490  	            try:
491  	                repo.git.checkout(current_branch)
492  	                repo.git.pull()
493  	            except git.GitCommandError:
(Pdb) n
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull
  stderr: 'hint: Pulling without specifying how to reconcile divergent branches is
hint: discouraged. You can squelch this message by running one of the following
hint: commands sometime before your next pull:
hint:
hint:   git config pull.rebase false  # merge (the default strategy)
hint:   git config pull.rebase true   # rebase
hint:   git config pull.ff only       # fast-forward only
hint:
hint: You can replace "git config" with "git config --global" to set a default
hint: preference for all repositories. You can also pass --rebase, --no-rebase,
hint: or --ff-only on the command line to override the configured default per
hint: invocation.
ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no: line 1: ssh: not found
fatal: Could not read from remote repository.
```
**Conclusion:** It is unable to execute git pull using SSH.

**To Reproduce**

1. Clone the repo using ssh method
2. run mega-linter
`docker run -d -ti -e GIT_SSH_COMMAND="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no" -e ENABLE_LINTERS=GROOVY_NPM_GROOVY_LINT -e PRINT_ALPACA=false -e VALIDATE_ALL_CODEBASE=false -e DEFAULT_BRANCH=origin/main -v ~/work/git/nc-cicd:/tmp/lint -v ~/.ssh_megalinter:/root/.ssh --entrypoint='./entrypoint.sh' nvuillam/mega-linter-ci_light:v4`
3. See warning

**Expected behavior**
No errors/warnings during execution

**Workaround**
Add **.mega-linter.yml** file in the repository with the following context:
```
PRE_COMMANDS:
  - command: apk add --update --no-cache openssh
    cwd: "root"
```

**Comment by noskovao** [comment]
Submitted for review small PR https://github.com/nvuillam/mega-linter/pull/728

**Comment by nvuillam** [comment]
Closed with your PR, thanks :)

**Comment by noskovao** [comment]
Thank you @nvuillam for your support and quick response!
