### ISSUE TITLE
[YAML_YAMLLINT] default config filename

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#742]
Hello,

I found strange the default `yamllint` config filename defined on [descriptor](https://github.com/nvuillam/mega-linter/blob/master/docs/descriptors/yaml_yamllint.md#readme) page by  `YAML_YAMLLINT_CONFIG_FILE` variable  ( `.yaml-lint.yml`) 
 while official yamllint documentation specify other names (https://yamllint.readthedocs.io/en/stable/configuration.html).

Could you clarify the situation ?

**Comment by nvuillam** [comment]
Mega-Linter is a hard-fork of Github Super-Linter, and yaml-lint.yml is the default file name there ^^

But it should be changed into .yamllint.yml ... but anyway, i think if a `.yamllint.yml` is defined , it will be used by yamllint :)

**Comment by llaville** [comment]
>  ... but anyway, i think if a `.yamllint.yml` is defined , it will be used by yamllint :)

Sorry, but it's not true, !

At least with `docker run -v $(pwd):/tmp/lint nvuillam/mega-linter-ci_light:v4` -- Mega-Linter v4.45

```
### Processed [YAML] files
- Using [yamllint v1.26.3] https://yamllint.readthedocs.io/
- Mega-Linter key: [YAML_YAMLLINT]
- Rules config: [.yaml-lint.yml]
```
Workaround is to specify `YAML_YAMLLINT_CONFIG_FILE: ".yamllint.yml"`

And I got expected result : 

```
### Processed [YAML] files
- Using [yamllint v1.26.3] https://yamllint.readthedocs.io/
- Mega-Linter key: [YAML_YAMLLINT]
- Rules config: [/.github/linters/.yamllint.yml]
```

**Comment by nvuillam** [comment]
Defaut Mega-Linter config file must have been taken :)

> > ... but anyway, i think if a .yamllint.yml is defined , it will be used by yamllint :)

> Sorry, but it's not true, !

I said I think, not I know :p 

Good workaround, I'll make the update someday, or you can also do it with a PR if you like :) ( CI is broken but i'll fix it soon)

**Comment by llaville** [comment]
👍 Thanks
