### ISSUE TITLE
Be able to deactivate CONSOLE reporter

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#743]
**Is your feature request related to a problem? Please describe.**
I'd like to write my own CONSOLE reporter (based on JSON reporter result), but with current version (4.45) it's not possible
See https://github.com/nvuillam/mega-linter/blob/master/docs/reporters/ConsoleReporter.md#configuration

**Describe the solution you'd like**
Add boolean `CONSOLE_REPORTER` variable with default true value to keep BC

**Comment by nvuillam** [comment]
Sure, i can implement that, or you can too if you're in a hurry :)

**Comment by llaville** [comment]
There are no hurry. Actually my console have both Mega-Linter output (first) then followed by my own console output based on JSON reporter (thanks to add it in v4.45, its help a lot)

**Comment by nvuillam** [comment]
Out of curiosity, can you show an example of your  custom output log ? :)

**Comment by llaville** [comment]
Wahoo ! I'll check in, have a look on this new feature, finish my console (normally this morning) and give you a look on it !

The need is to replace the current Makefile in project https://github.com/devilbox/flames.
As I'm not the maintainer of this repo, even If I've initiated the project 2 years ago, I've a fork available at https://github.com/llaville/flames
I'll keep the Makefile, but run Mega-Linter locally with docker, and analyze results with JSON reporter and [jq](https://github.com/stedolan/jq) tool to extract data from json stream. 
 
Actually, the original `make lint` command give somehing like 

![flames](https://user-images.githubusercontent.com/364342/133917231-a0ed9147-99bb-4acc-9c1a-e59ecc666249.png)

And replacement, should follows the same presentation

**Comment by llaville** [comment]
And with commit https://github.com/llaville/flames/commit/d7cf1cb1fcb1e95201dc717d00e3b15b2362e593, I'm able to produce something equal, but with Mega-Linter and jq

![make_lint](https://user-images.githubusercontent.com/364342/133919877-f1f468dd-b999-4167-b54d-98f853745c10.png)
