### ISSUE TITLE
CLI lint mode not applied to GolangCI

### ISSUE THREAD

**Issue by FedorLap2006** [nvuillam/mega-linter#757]
**Describe the bug**
`GO_GOLANGCI_LINT_CLI_LINT_MODE` is not applied to `golangci-lint` therefore `golangci-lint` goes through each file and throws a lot of errors about non-existing types.

**To Reproduce**

1. Set `GO_GOLANGCI_LINT_CLI_LINT_MODE` to `project`
2. Enable golangci linter
3. See the error

**Expected behavior**
GolangCI running from project root and not throwing non-existing type errors

**Screenshots**
![image](https://user-images.githubusercontent.com/42876964/134202462-456ad122-0909-459b-987f-6f2b2e924c67.png)

**Comment by nvuillam** [comment]
Are you using insiders/latest version ?
Override of cli_lint_mode is not released in v4 yet

**Comment by FedorLap2006** [comment]
Nope, used `v4`, how do I use latest version?

**Comment by nvuillam** [comment]
I'm currently releasing v4.46.0 (and it will replace v4), so in a few dozen minutes your case should work :)

Explanation: 
- At each new commit in master (from merge request), it is published as [preview](https://nvuillam.github.io/mega-linter/CHANGELOG/#unreleased-master-branch)
- Documentation is not versionned so it contains latest updates, even if they are not in official releases yet

When [this Github action job](https://github.com/nvuillam/mega-linter/runs/3668061093?check_suite_focus=true) will be complete, v4 will contain management of cli_lint_mode override, and you'll be able to try again :)

**Comment by FedorLap2006** [comment]
Thank you.

**Comment by nvuillam** [comment]
@FedorLap2006 does it work like you wish now ? :)

**Comment by FedorLap2006** [comment]
Yup, works well
