### ISSUE TITLE
[v4.46] PHP 8.0 not supported

### ISSUE THREAD

**Issue by llaville** [nvuillam/mega-linter#788]
**Describe the bug**
Side effects may be found when using Mega-Linter GA with other Github Actions that use PHP Platform

**To Reproduce**

1. Use a GA workflow with multiple steps, including https://github.com/ramsey/composer-install to install Composer dependencies of a PHP project (for [example](https://github.com/llaville/php-compatinfo-db/blob/810f86f5c19fe870b92fbefbffb30a6b35e354b6/.github/workflows/php-tests.yaml#L32-L37))
2. Use a Mega-Linter PHP flavor step (like `nvuillam/mega-linter/flavors/php@v4`) 
3. Be sure to have PHP_PHPSTAN linter enabled in project mode to avoid issue #725) for [example](https://github.com/llaville/php-compatinfo-db/blob/810f86f5c19fe870b92fbefbffb30a6b35e354b6/.mega-linter.yml#L20)
3. Run GA workflow
4. See error in screenshot; full GA report available at https://github.com/llaville/php-compatinfo-db/runs/3729299344?check_suite_focus=true

**Expected behavior**
Be able to configure Mega-Linter to accept PHP versions other than PHP 7.x or a better catching error about PHP platform

**Screenshots**

![phpstan_php8](https://user-images.githubusercontent.com/364342/135047811-7f6fb703-b4ba-4d92-a75e-1e03abbe8cec.png)

**Additional context**
Mega-Linter v4.46 only support PHP 7 (confirmed by https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/descriptors/php.megalinter-descriptor.yml#L7-L19)

**Comment by llaville** [comment]
As workaround we can use `shivammathur/setup-php` GA as specified https://github.com/ramsey/composer-install#usage
For example in the same context project as previous : https://github.com/llaville/php-compatinfo-db/commit/8db3e4b5162496568a8aea72443afe3d9a6bb126

**Comment by nvuillam** [comment]
Maybe you'd like to make a PR to update php install instructions so PHP8 is natively handled ? :)

**Comment by llaville** [comment]
Does it make sense for you to keep major PHP versions as different flavor ? Please vote !
That's mean a `php7` and `php8` instead of just a `php`

**Comment by llaville** [comment]
@nvuillam Finally, after study carefully source code of Mega-Linter, there is no need to have a different flavor for PHP 7 and PHP 8, as previously suggested.

Solution is to use ability to [override executable](https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/Linter.py#L143-L144) and make it available at runtime with a new env var as follow `PHP_BUILTIN_CLI_EXECUTABLE: "/usr/bin/php8"`, Default will be None and used linter name as executable.

And of course https://github.com/nvuillam/mega-linter/blob/v4.46.0/megalinter/descriptors/php.megalinter-descriptor.yml#L7-L19 will be updated to add php8 and modules both with existing php7 copies 

If you are agree with it, a PR may follows

**Comment by nvuillam** [comment]
Go ! :)
