### ISSUE TITLE
Is ansible-lint version 0.0.0 right?

### ISSUE THREAD

**Issue by jjcaballero** [nvuillam/mega-linter#792]
**Describe the bug**
The displayed version of ansible-lint is v0.0.0.

Also, I am getting quite different results when using ansible-lint as standalone tool and use it through mega-linter. This could be a mismatch between versions but I can't say. The true is that mega-linter results are suspectingly too clean. It only detects clear errors indentation or using wrong keywords. But without, knowing the ansible-lint version used, there is no point to compare the reported errors.

**To Reproduce**
```
 mkdir ansible
 touch ansible/playbook.yml
 docker run -v $PWD:/tmp/lint nvuillam/mega-linter
 ...
  - Using [ansible-lint v0.0.0]
 ...
```

**Expected behavior**
- Display the current version used of ansible-lint.
- If version 0.0.0 is right, please update to a more modern version, ideally the latest one.

**Comment by nvuillam** [comment]
It's not 0.0.0 :)
If i hardcoded it, it's probably because `ansible-lint --version` did not work, is it still the case ?

**Comment by jjcaballero** [comment]
Good! Which version is currently used?

`ansible --version` does not work without `ansible`.  I don't know if there is some other functionality missing when using it without `ansible`.

From a virtual enviroment with both:
```
$ ansible-lint --version
ansible-lint 5.1.3 using ansible 2.11.5
```

If in the future, I would like to check the `anible-lint` version used in `mega-linter`, can you please share instructions to do so? (e.g.: source code, from the docker image running a container interactively, ...). Thanks.
