### ISSUE TITLE
Various issues

### ISSUE THREAD

**Issue by GrabCAD-Gary** [nvuillam/mega-linter#793]
Hi,

I've been looking at implementing Mega-Linter in our workflows and run into several unexpected issues and questions. I'll raise them here and I can make the necessary bug reports if they turn out to be more than just me getting things wrong.

1. I can't find a way to run spelling checkers as I expect to. Enabling CSPELL alone does nothing because it seems as though it's fed whatever files are found by other linters i.e. if I enable YAML then the .yml files are found and only those files are spell-checked. This seems very odd. Wanting to run spelling checks independantly of other checks seems like a blindingly obvious thing. Is there a way to do this?

2. I have been unable to determine whether checking changed files only relies on GIT_DIFF, VALIDATE_ALL_CODEBASE or both. I have found no way to do it locally, although it works on GitHub correctly. No combination of those settings ever causes M-L to check changed files only when run locally.

3. Linting stops with:
```
  [Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/ERROR-YAML_PRETTIER.log
  Traceback (most recent call last):
    File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 167, in run
    reporter.produce_report()
  File "/megalinter/reporters/ConfigReporter.py", line 103, in produce_report
    vscode_extensions_config = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 2 (char 3)
```
I had this pinned down to cspell until I found that it happens when I enable YAML as well. I checked every JSON file in the repo and none of them have any errors so this seems to be internal. I tried both dotnet and javascript flavours and both have the same issue.

4. Generated files don't pass linting!! This is true of the .mega-linter.yml for the linters and for the GH action and others. That seems pretty poor.

5. Linting is horribly slow for some operations. I can run GIT, YAML and SPELL and have results in about a minute using the javascript and dotnet flavours. If I run POWERSHELL it's about an hour. As I write I have GIT and JSON enabled. M-L found 1467 JSON files to lint, it's been going for over an hour and last reported
```
✅ Linted [JSON] files with [v8r] successfully - (2845.17s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/SUCCESS-JSON_V8R.log
```
towards an hour ago. It's not usable at that rate of progress and no linter should take that long. Again, something more seems wrong especially given that they run in parallel. I did note that Docker prompted that I had files shared with WSL, presumably because I used the WSL2 back-end. I've changed that back to default which stopped Docker prompting but hasn't helped.

6. I'm using VSCode. The name completion mentioned on the configuration page doesn't work for ENABLE_LINTERS and DISABLE_LINTERS. That's because they're not in the schema, which seems like an oversight.

Any guidance you can offer is appreciated. I may be doing things wrong somewhere. I have some settings in my .mega-linter.yml and I have tried juggling them to see if anything changes but haven't detected that it does.

Many thanks.

**Comment by GrabCAD-Gary** [comment]
UPDATE:
The run mentioned above finshed after somewhere around two hours. The output was then:
```
✅ Linted [JSON] files with [v8r] successfully - (2845.17s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/SUCCESS-JSON_V8R.log
Unable to get number of errors with regex_sum and ✖ ([0-9]+) problem                 # <===================

### Processed [JSON] files
- Using [eslint-plugin-jsonc v1.6.0] https://ota-meshi.github.io/eslint-plugin-jsonc/
- Mega-Linter key: [JSON_ESLINT_PLUGIN_JSONC]
- Rules config: [.eslintrc-json.json]
```
It then continued with `eslint-plugin-jsonc`  which finished with
```
--Error detail:

<--- Last few GCs --->
) [25:0x7fd23fcc3030]  5174193 ms: Mark-sweep (reduce) 992.5 (1010.8) -> 992.5 (1011.0) MB, 1392.6 / 0.0 ms  (+ 4.5 ms in 1 steps since start of marking, biggest step 4.5 ms, walltime since start of marking 1397 ms) (average mu = 0.667, current mu = 0.000) [25:0x7fd23fcc3030]  5175927 ms: Mark-sweep (reduce) 992.8 (1011.0) -> 992.7 (1011.3) MB, 1729.4 / 0.0 ms  (+ 4.1 ms in 1 steps since start of marking, biggest step 4.1 ms, walltime since start of marking 1734 ms) (average mu = 0.476, current mu = 0.000)

<--- JS stacktrace --->

FATAL ERROR: MarkCompactCollector: young object promotion failed Allocation failed - JavaScript heap out of memory
```

and then the same
```
❌ Linted [JSON] files with [eslint-plugin-jsonc]: Found 1 error(s) - (5222.07s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/ERROR-JSON_ESLINT_PLUGIN_JSONC.log
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/megalinter/run.py", line 15, in <module>
    linter.run()
  File "/megalinter/MegaLinter.py", line 167, in run
    reporter.produce_report()
  File "/megalinter/reporters/ConfigReporter.py", line 103, in produce_report
    vscode_extensions_config = json.load(json_file)
  File "/usr/local/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 2 column 2 (char 3)
```
😢

**Comment by nvuillam** [comment]
Seems lots of issues... I'm sure we can find solutions for at least most of them :)

What version of mega linter are you using, and how do you run it ? ( Ci ? mega-linter-runner ? )

**Comment by GrabCAD-Gary** [comment]
npx and V4. Thanks.

**Comment by GrabCAD-Gary** [comment]
The latest run also threw errors out of markdown lint:
```
✅ Linted [MARKDOWN] files with [markdownlint]: Found 812 non blocking error(s) - (13.72s)
[Text Reporter] Generated TEXT report: /tmp/lint/report/linters_logs/ERROR-MARKDOWN_MARKDOWNLINT.log
Unable to get number of errors with regex_sum and ERROR: ([0-9]+) dead links found
Unable to get number of errors with regex_sum and ERROR: ([0-9]+) dead links found
...
```
It looks like one error line per result, possibly. Around 100 of them. Linting continued successfully from there.

**Comment by nvuillam** [comment]
> I can't find a way to run spelling checkers as I expect to. Enabling CSPELL alone does nothing because it seems as though it's fed whatever files are found by other linters i.e. if I enable YAML then the .yml files are found and only those files are spell-checked. This seems very odd. Wanting to run spelling checks independantly of other checks seems like a blindingly obvious thing. Is there a way to do this?

Usually people want to check the spelling of the files they lint 
But if you want to check everything, you may try to add `SPELL_CSPELL_CLI_LINT_MODE: project` in your .mega-linter.yml file

> I have been unable to determine whether checking changed files only relies on GIT_DIFF, VALIDATE_ALL_CODEBASE or both. I have found no way to do it locally, although it works on GitHub correctly. No combination of those settings ever causes M-L to check changed files only when run locally.

As described in [documentation](https://nvuillam.github.io/mega-linter/descriptors/git_git_diff/), GIT_DIFF is the name of a "linter" that checks if the sources contain unsolved git conflicts markers.
`VALIDATE_ALL_CODEBASE : false` will make that for most of linters (not the ones with cli_lint_mode == project) will analyze only the files that changed between the current branch and the pull request target branch.

> Linting stops with: ...

You probably have a .vscode/extensions.json that contains comments. python default json parser does not like that ... but I think I remember that vscode creates json with comments by default, so I'll find another parser that accepts JSONC. Meanwhile, you can just remove the comments of the workaround :)

> Generated files don't pass linting!! This is true of the .mega-linter.yml for the linters and for the GH action and others. That seems pretty poor.

Maybe, that's something to add in the to-do list ^^ But in the reports folder, you can find updated_files that contains the auto-fixes.
If you configure auto-fix, a new commit will automatically be pushed.

> Linting is horribly slow for some operations. I can run GIT, YAML and SPELL and have results in about a minute using the javascript and dotnet flavours. If I run POWERSHELL it's about an hour. As I write I have GIT and JSON enabled. M-L found 1467 JSON files to lint, it's been going for over an hour and last reported

v8r checks for each JSON and YAML
- if there is a schema on schemastore.com
- if found, validate the file according to the JSON schema

To enhance performances, you can:
- disable linters or languages
- add _linter_name_ _FILTER_REGEX_EXCLUDE for some linters or languages
- add [FILTER_REGEX_EXCLUDE](https://nvuillam.github.io/mega-linter/configuration/#filter-linted-files) for all linters (maybe on the folder containing all your json files ?)

> I'm using VSCode. The name completion mentioned on the configuration page doesn't work for ENABLE_LINTERS and DISABLE_LINTERS. That's because they're not in the schema, which seems like an oversight.

Do you have Red Hat YAML extension ? Defaut VsCode does not manage schemastore.com-based auto-completion

![image](https://user-images.githubusercontent.com/17500430/135526703-fb430685-5708-45d2-b90c-e4ec901dd9bc.png)

**Comment by nvuillam** [comment]
About the other issues... it seems that the linter, or the CI machines require too many system resources... you project must be pretty big

What so many json files ? Maybe they are generated ? In that case there is no reason to lint them, you should do something like `FILTER_REGEX_EXCLUDE: (path/to/json/files/.*\.json)`

Some linters like CSPELL or JSCPD do not care about FILTER_REGEX_EXCLUDE, you must ignore files using their own config file, like explained in [jscpd documentation](https://nvuillam.github.io/mega-linter/descriptors/copypaste_jscpd/)

**Comment by GrabCAD-Gary** [comment]
Thanks for taking the time to reply. This shouldn't be closed, we're a long way from working yet. I can't re-open it. I presume you have disabled that option. Please re-open it.

> 
> Usually people want to check the spelling of the files they lint But if you want to check everything, you may try to add `SPELL_CSPELL_CLI_LINT_MODE: project` in your .mega-linter.yml file
> 

That's an assumption. I can work with that as a limitation, though. Understanding what it's doing is the first barrier. Thanks.

> 
> As described in [documentation](https://nvuillam.github.io/mega-linter/descriptors/git_git_diff/), GIT_DIFF is the name of a "linter" that checks if the sources contain unsolved git conflicts markers. `VALIDATE_ALL_CODEBASE : false` will make that for most of linters (not the ones with cli_lint_mode == project) will analyze only the files that changed between the current branch and the pull request target branch.
> 

Yes, I know, but nothing tells me what precisely is being used to determine which files have changed and that is the obvious candidate. `VALIDATE_ALL_CODEBASE : false`  has no visible effect on any of the linters I've tried at all. They still find exactly the same numbers of files and lint them. The difference should be obvious since no files of those types have changed in most cases.

> You probably have a .vscode/extensions.json that contains comments. python default json parser does not like that ... but I think I remember that vscode creates json with comments by default, so I'll find another parser that accepts JSONC. Meanwhile, you can just remove the comments of the workaround :)
> 

You're right. Thanks.

> > Linting is horribly slow for some operations... 
> 
> v8r checks for each JSON and YAML
> 
>     * if there is a schema on schemastore.com
> 
>     * if found, validate the file according to the JSON schema
> 
> 
> To enhance performances, you can:
> 
>     * disable linters or languages
> 
>     * add _linter_name_ _FILTER_REGEX_EXCLUDE for some linters or languages
> 
>     * add [FILTER_REGEX_EXCLUDE](https://nvuillam.github.io/mega-linter/configuration/#filter-linted-files) for all linters (maybe on the folder containing all your json files ?)
> 

I have done some of this. Thanks for the pointer regarding some linters needing specific instructions. That's good to know. I also have global exclusions in place for the obvious things.

> 
> Do you have [Red Hat YAML extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml) ? Defaut VsCode does not manage schemastore.com-based auto-completion
> 

I do.

> ![image](https://user-images.githubusercontent.com/17500430/135526703-fb430685-5708-45d2-b90c-e4ec901dd9bc.png)

It doesn't work here. This specific completion doesn't appear, either. None appear in `ENABLE_LINTERS`. There's a problem somewhere.

The biggest issue I currently have is outsdie these, though. See here. please.

**Comment by GrabCAD-Gary** [comment]
Some additional points regarding spelling checks. Spelling checking refuses to run at all unless I enable a language linter to find the files. When a language linter is specified
```
SPELL_MISSPELL_CLI_LINT_MODE: project
SPELL_CSPELL_CLI_LINT_MODE: project
```
don't do anything when
```
ENABLE:
    - SPELL
```

is set i.e. M-L still lists them as being set to `file`. They do work when 
```
ENABLE_LINTERS:
    - SPELL_CSPELL
    - SPELL_MISSPELL
```
are set but, even then, the checkers only appear to check the files found by the language linter. I can work with them together with the language linters. This is just for info.

**Comment by nvuillam** [comment]
I'll try to have a lookat all that, but please csn you open one issue by problem ?
That way, they can be read, fixed and closed one by one

**Comment by GrabCAD-Gary** [comment]
👍

**Comment by appmakerusa** [comment]
I am also seeing the same heap memory error. Is there any resolution? Thanks in advance.

<--- Last few GCs --->

[57:0x7f07d8e292b0]   644782 ms: Mark-sweep 2006.1 (2070.1) -> 1990.2 (2069.6) MB, 2841.6 / 0.0 ms  (average mu = 0.142, current mu = 0.002) allocation failure scavenge might not succeed
[57:0x7f07d8e292b0]   648651 ms: Mark-sweep 2006.2 (2069.6) -> 1990.2 (2069.8) MB, 3862.8 / 0.0 ms  (average mu = 0.066, current mu = 0.002) allocation failure scavenge might not succeed

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory

**Comment by nvuillam** [comment]
@appmakerusa I made a PR to try to increase --max-old-space-size to 8192 (8gb) , let's see if it solves the issue :)

**Comment by appmakerusa** [comment]
Hello @nvuillam, unfortunately the increased space size did not solve the issue. Here is a diff showing the result before PR (top) and result after PR (bottom). 
![image](https://user-images.githubusercontent.com/53278248/150408317-e247b0bd-62cd-48a1-b3f1-e611b7cc2bb5.png)

**Comment by appmakerusa** [comment]
@nvuillam the problem is solved with running the beta version. Thanks! 👍

**Comment by nvuillam** [comment]
> @nvuillam the problem is solved with running the beta version. Thanks! 👍 

That's great, i should release a new minor version this weekend :)

**Comment by GrabCAD-Gary** [comment]
...and I'm still monitoring this so I'll try and test it here next week. Thanks.

**Comment by GrabCAD-Gary** [comment]
I do see some good speed improvements across the board. That's great. Have you considered making the amount of memory provided to Java configurable so we can adjust it ourselves? That would allow us to throw more memory at it if we have it available.

Also, the configuration docs say that parallel execution is the default:

> PARALLEL
>Process linters in parallel to improve overall MegaLinter performance. If true, linters of same language or formats are grouped in the same parallel process to avoid lock issues if fixing the same files

What would it take to allow all linters to execute in parallel if `APPLY_FIXES:` is set to `none`? Given that linters are not writing changes to files, we should have no trouble running them that way. That might provide some substantial performance improvements, especially if we can give it more memory easily. Is that something that could be considered?

Thanks for your efforts.

**Comment by nvuillam** [comment]
@GrabCAD-Gary 

**Java memory**
How would you like to do that ? If it's by linter, it is already possible to define additional arguments to the commands , so `-Xms<size> could be sent`
If there is a generic way to do that for all java apps called ?

**Parallel:**
if there are no linters defined to do fixes, they are already all processed in parallel :)
Else, they are parallel but grouped by descriptor

![image](https://user-images.githubusercontent.com/17500430/152212170-bd706b29-0dcb-4cb1-a7d4-4e4e8d94e1a1.png)

**Comment by GrabCAD-Gary** [comment]
> @GrabCAD-Gary
> 
> **Java memory** How would you like to do that ? If it's by linter, it is already possible to define additional arguments to the commands , so `-Xms<size> could be sent` If there is a generic way to do that for all java apps called ?
> 

I was thinking of a setting in `.mega-linter.yaml` that would be passed on to each linter. This would be a simpler option and the linter-specific options would still be useful if we wanted to make adjustments to individual linters. What do you think?

> **Parallel:** if there are no linters defined to do fixes, they are already all processed in parallel :) Else, they are parallel but grouped by descriptor

Beautiful. It's also a shame as I was hoping we could kick the speed up another notch. 😉
For me, linting a few MD files takes ~3-4 mins. The linters themselves takes under 10 secs according to the report and that's with table, link and spelling checking enabled. `npx` takes about 90 secs to install what it needs, so that won't change. It's the price we pay for not installing it. That still leaves 2.5 - 3.5 mins for ML to churn. Writing reports seems quite slow judging by what the output says. Maybe that's an area we could accelerate?

I'd be interested to see how fast it would go if I could give it a lot more memory. Maybe I'll tinker with the linter's settings as you suggest, just to see what happens.

**Comment by nvuillam** [comment]
@GrabCAD-Gary 

> I was thinking of a setting in .mega-linter.yaml that would be passed on to each linter. This would be a simpler option and the linter-specific options would still be useful if we wanted to make adjustments to individual linters. What do you think?

Not all linter are java based... or java is called internally
Do you have a problem with a java-based linter in particular ?

> Beautiful. It's also a shame as I was hoping we could kick the speed up another notch. 😉
No offense taken :D 

> For me, linting a few MD files takes ~3-4 min
Are they full of hyperlinks ? If yes, it's because markdown-link-check tries all links, and if they are links to github for examples, it quickly reaches "too many calls" response, so it waits, tries again, etc...

> npx takes about 90 secs to install what it needs, so that won't change
do you use npx mega-linter-runner ? You may use megalinter/megalinter docker image directly, it will be faster :)

> Writing reports seems quite slow judging by what the output says. Maybe that's an area we could accelerate?
Please share your final results table, or even the full log after adding LOG_LEVEL: DEBUG in .mega-linter.yml, and let's see what we can improve :)

**Comment by appmakerusa** [comment]
@nvuillam was this implemented? I would like to change the line length parameter for CPPLINT. Default is 80. I want mega-linter-runner to be able to pass to it the following parameter via the .mega-linter.yaml file.
**cpplint.py --linelength=120**

**Comment by GrabCAD-Gary** [comment]
> Not all linter are java based... or java is called internally Do you have a problem with a java-based linter in particular ?

Not specifically.

> > npx takes about 90 secs to install what it needs, so that won't change
> 
> do you use npx mega-linter-runner ? You may use megalinter/megalinter docker image directly, it will be faster :)

How would I do that?

> Please share your final results table, or even the full log after adding LOG_LEVEL: DEBUG in .mega-linter.yml, and let's see what we can improve :)

Sorry, I didn't get back to this at the time. I may get a change sometime soon. I'm not sure why that would help, though. I'm sure you're aware of how it runs the reports. One thing that seems very odd is the split between the SUCCESS and ERROR reports, especially given that there are not time stamps in them and the SUCCESS ones aren't removed if a subsequent ERROR report is written and vice versa. That's very strange and very unhelpful as you can't tell in any obvious way which is the latest. I would have expected one log per linter with a time stamp in it and possibly an option for how much history to retain.
