### ISSUE TITLE
How to exclude .vue from jscpd?

### ISSUE THREAD

**Issue by BunnyTheLifeguard** [nvuillam/mega-linter#806]
![image](https://user-images.githubusercontent.com/36411819/135900615-34361a69-4fdd-4ba3-8a1e-096026660e6c.png)

I've read through it a couple of times, but can't figure our how to exclude .vue

Is it `[".vue", ""]`, `[".vue", "*"]` or something completely different? 😅

**Comment by BunnyTheLifeguard** [comment]
Hey thanks for the quick reply ^^
Yeah I got it to work like that, was just wondering if there is a way with the above setting to avoid cluttering the folder with another one of those files (.eslints, .gitlab-ci, .mega-linter, .prettier, .releasesrc, ...) :D

**Comment by nvuillam** [comment]
You can, by creating a folder , put linter config files in it, and define mega linter variables so they are used :)

**Comment by BunnyTheLifeguard** [comment]
Will look into that one, my dude (:
But the .yml files need to stay in root, no? Am pretty new to gitlab ci/cd 😅

**Comment by nvuillam** [comment]
It's very common to have gitlab-ci.yml at the root, but if you prefer another location you can override it in gitlab ci/cd settings :)

**Comment by BunnyTheLifeguard** [comment]
For sure, but I can at least put the mega-linter config in a separate folder and include the path in `MEGALINTER_CONFIG` right?

**Comment by nvuillam** [comment]
I've never seen it used like that (only for remote configuration) but it should work yes :)
