### ISSUE TITLE
Support Filtering Via Mega-Linter Config Variables for Secretlint

### ISSUE THREAD

**Issue by Kurt-von-Laven** [nvuillam/mega-linter#816]
**Is your feature request related to a problem? Please describe.**
A separate .secretlintignore needs to be maintained for Secretlint, which introduces redundancy with the excluded file and directories in .mega-linter.yaml.

**Describe the solution you'd like**
Secretlint ignores files that Mega-Linter is configured to ignore.

**Describe alternatives you've considered**
This might be the wrong place to file this feature request. I am not sure whether some or all of this work would be best done by Secretlint upstream. An alternative might be to introduce support for parsing gitignore to Secretlint, for example.

**Additional context**
I'm not aware of any other linters within Mega-Linter that don't support filtering via Mega-Linter config variables.

**Comment by nvuillam** [comment]
When linters can be run only on the whole root directory, FILTER_REGEX_(IN/EX)CLUDE are not taken in account, the only way is to define ignore config in the linter config file, like .secretlintignore

To automatize that, we would need to generate "on the fly" a .secretlintignore using regex values... I don't really know how to do that :/

**Comment by Kurt-von-Laven** [comment]
In retrospect that seems obvious; thank you for explaining. While that seems theoretically possible, it seems overly complex since it would have to handle cases where the user did and didn't already have .secretlintignore or an alternatively named Secretlint ignore file. I am closing this in favor of requesting .gitignore parsing from Secretlint itself.

**Comment by nvuillam** [comment]
@Kurt-von-Laven > anyway... except maybe or some test classes containing fake credentials, I don't see lots of cases where we should ignore repo content containing hardcoded secrets ^^

**Comment by Kurt-von-Laven** [comment]
Probably only really comes up when Secretlint has a lot of false positives, but I personally haven't known it to struggle much with that.
